import { Router } from "express";
import bcrypt from "bcryptjs";
import multer from "multer";
import { randomBytes } from "node:crypto";
import { z } from "zod";
import { pool, query } from "./db.js";
import { requireAuth, requireSiteAdmin, signToken } from "./auth.js";

export const routes = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024, files: 1 } });
const userSelect = `id,username,display_name AS "displayName",real_name AS "realName",email,site_role AS "siteRole",CASE WHEN avatar_id IS NULL THEN NULL ELSE '/api/attachments/'||avatar_id END AS "avatarUrl",CASE WHEN banner_id IS NULL THEN NULL ELSE '/api/attachments/'||banner_id END AS "bannerUrl"`;
const roomMediaSelect = `CASE WHEN r.icon_id IS NULL THEN NULL ELSE '/api/attachments/'||r.icon_id END AS "iconUrl",CASE WHEN r.banner_id IS NULL THEN NULL ELSE '/api/attachments/'||r.banner_id END AS "bannerUrl"`;

routes.get("/health", (_req, res) => res.json({ ok: true }));
routes.get("/attachments/:id", async (req, res, next) => { try {
  const result = await query<{ filename: string; mime_type: string; content: Buffer }>("SELECT filename,mime_type,content FROM attachments WHERE id=$1", [req.params.id]); const file = result.rows[0]; if (!file) return res.status(404).end();
  res.setHeader("Content-Type", file.mime_type); res.setHeader("Content-Disposition", `inline; filename*=UTF-8''${encodeURIComponent(file.filename)}`); res.setHeader("Cache-Control", "public, max-age=31536000, immutable"); res.send(file.content);
} catch (error) { next(error); } });

routes.post("/auth/register", async (req, res, next) => { try {
  const data = z.object({ username: z.string().regex(/^[a-zA-Z0-9_]{3,32}$/), password: z.string().min(8).max(100), displayName: z.string().min(2).max(50), realName: z.string().min(3).max(100), email: z.string().email().max(254) }).parse(req.body);
  const passwordHash = await bcrypt.hash(data.password, 12); const siteRole = data.username.toLowerCase() === "arcanjoraziel" && data.email.toLowerCase() === "azazjogos@gmail.com" ? "superadmin" : "user";
  const result = await query<any>(`INSERT INTO users(username,display_name,real_name,email,password_hash,site_role) VALUES(lower($1),$2,$3,lower($4),$5,$6) RETURNING ${userSelect}`, [data.username, data.displayName, data.realName, data.email, passwordHash, siteRole]); const user = result.rows[0]; res.status(201).json({ token: signToken(user), user });
} catch (error) { next(error); } });
routes.post("/auth/login", async (req, res, next) => { try {
  const data = z.object({ username: z.string().min(3), password: z.string().min(8).max(100) }).parse(req.body); const result = await query<any>(`SELECT ${userSelect},password_hash FROM users WHERE username=lower($1)`, [data.username]); const row = result.rows[0]; if (!row || !(await bcrypt.compare(data.password, row.password_hash))) return res.status(401).json({ error: "Usuário ou senha inválidos" }); delete row.password_hash; res.json({ token: signToken(row), user: row });
} catch (error) { next(error); } });

routes.use(requireAuth);
routes.get("/me", async (req, res, next) => { try { const result = await query(`SELECT ${userSelect} FROM users WHERE id=$1`, [req.user!.id]); res.json(result.rows[0]); } catch (error) { next(error); } });
routes.patch("/me", async (req, res, next) => { try {
  const data = z.object({ username: z.string().regex(/^[a-zA-Z0-9_]{3,32}$/).optional(), displayName: z.string().min(2).max(50).optional(), avatarId: z.string().uuid().nullable().optional(), bannerId: z.string().uuid().nullable().optional() }).refine((value) => Object.keys(value).length > 0).parse(req.body);
  for (const attachmentId of [data.avatarId, data.bannerId]) if (attachmentId) { const image = await query("SELECT 1 FROM attachments WHERE id=$1 AND uploaded_by=$2 AND mime_type LIKE 'image/%'", [attachmentId, req.user!.id]); if (!image.rowCount) return res.status(400).json({ error: "Imagem inválida" }); }
  const result = await query<any>(`UPDATE users SET username=coalesce(lower($1),username),display_name=coalesce($2,display_name),avatar_id=CASE WHEN $3::boolean THEN $4::uuid ELSE avatar_id END,banner_id=CASE WHEN $5::boolean THEN $6::uuid ELSE banner_id END WHERE id=$7 RETURNING ${userSelect}`,
    [data.username ?? null, data.displayName ?? null, data.avatarId !== undefined, data.avatarId ?? null, data.bannerId !== undefined, data.bannerId ?? null, req.user!.id]);
  const user = result.rows[0]; res.json({ user, token: signToken(user) });
} catch (error) { next(error); } });
routes.get("/rooms", async (req, res, next) => { try { const result = await query(`SELECT r.id,r.name,r.slug,r.created_by AS "createdBy",m.role,${roomMediaSelect} FROM rooms r JOIN memberships m ON m.room_id=r.id WHERE m.user_id=$1 ORDER BY r.name`, [req.user!.id]); res.json(result.rows); } catch (error) { next(error); } });
routes.post("/rooms", async (req, res, next) => { const client = await pool.connect(); try {
  const data = z.object({ name: z.string().min(2).max(60) }).parse(req.body); const slug = `${data.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}-${randomBytes(3).toString("hex")}`;
  await client.query("BEGIN"); const room = (await client.query("INSERT INTO rooms(name,slug,created_by) VALUES($1,$2,$3) RETURNING id,name,slug,created_by AS \"createdBy\",NULL::text AS \"iconUrl\",NULL::text AS \"bannerUrl\"", [data.name, slug, req.user!.id])).rows[0]; await client.query("INSERT INTO memberships(room_id,user_id,role) VALUES($1,$2,'owner')", [room.id, req.user!.id]); await client.query("INSERT INTO channels(room_id,name,kind) VALUES($1,'geral','text'),($1,'Geral','voice')", [room.id]); await client.query("COMMIT"); res.status(201).json({ ...room, role: "owner" });
} catch (error) { await client.query("ROLLBACK"); next(error); } finally { client.release(); } });
routes.patch("/rooms/:roomId", async (req, res, next) => { try {
  const data = z.object({ name: z.string().min(2).max(60).optional(), iconId: z.string().uuid().nullable().optional(), bannerId: z.string().uuid().nullable().optional() }).refine((value) => Object.keys(value).length > 0).parse(req.body);
  const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role IN ('owner','admin')", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" });
  for (const attachmentId of [data.iconId, data.bannerId]) if (attachmentId) { const image = await query("SELECT 1 FROM attachments WHERE id=$1 AND uploaded_by=$2 AND mime_type LIKE 'image/%'", [attachmentId, req.user!.id]); if (!image.rowCount) return res.status(400).json({ error: "Imagem inválida" }); }
  const result = await query<any>(`UPDATE rooms r SET name=coalesce($1,name),icon_id=CASE WHEN $2::boolean THEN $3::uuid ELSE icon_id END,banner_id=CASE WHEN $4::boolean THEN $5::uuid ELSE banner_id END WHERE id=$6 RETURNING r.id,r.name,r.slug,r.created_by AS "createdBy",${roomMediaSelect}`,
    [data.name ?? null, data.iconId !== undefined, data.iconId ?? null, data.bannerId !== undefined, data.bannerId ?? null, req.params.roomId]); res.json(result.rows[0]);
} catch (error) { next(error); } });

routes.get("/rooms/:roomId/channels", async (req, res, next) => { try { const result = await query(`SELECT c.id,c.room_id AS "roomId",c.name,c.kind,EXISTS(SELECT 1 FROM channel_access ca WHERE ca.channel_id=c.id) AS restricted FROM channels c JOIN memberships m ON m.room_id=c.room_id WHERE c.room_id=$1 AND m.user_id=$2 AND ($3='superadmin' OR m.role IN ('owner','admin') OR NOT EXISTS(SELECT 1 FROM channel_access ca WHERE ca.channel_id=c.id) OR EXISTS(SELECT 1 FROM channel_access ca WHERE ca.channel_id=c.id AND ca.user_id=$2)) ORDER BY c.kind,c.created_at`, [req.params.roomId, req.user!.id, req.user!.siteRole ?? "user"]); res.json(result.rows); } catch (error) { next(error); } });
routes.post("/rooms/:roomId/channels", async (req, res, next) => { try {
  const data = z.object({ name: z.string().min(1).max(40), kind: z.enum(["text", "voice"]), allowedUserIds: z.array(z.string().uuid()).optional() }).parse(req.body); const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role IN ('owner','admin')", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" });
  const client = await pool.connect(); try { await client.query("BEGIN"); const channel = (await client.query("INSERT INTO channels(room_id,name,kind) VALUES($1,$2,$3) RETURNING id,room_id AS \"roomId\",name,kind", [req.params.roomId, data.name, data.kind])).rows[0]; for (const userId of data.allowedUserIds ?? []) await client.query("INSERT INTO channel_access(channel_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING", [channel.id, userId]); await client.query("COMMIT"); res.status(201).json({ ...channel, restricted: !!data.allowedUserIds?.length }); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
} catch (error) { next(error); } });
routes.get("/channels/:channelId/access", async (req, res, next) => { try { const result = await query("SELECT user_id AS \"userId\" FROM channel_access WHERE channel_id=$1", [req.params.channelId]); res.json(result.rows.map((row: any) => row.userId)); } catch (error) { next(error); } });
routes.put("/channels/:channelId/access", async (req, res, next) => { const client = await pool.connect(); try { const userIds = z.object({ userIds: z.array(z.string().uuid()) }).parse(req.body).userIds; const allowed = req.user!.siteRole === "superadmin" || !!(await client.query("SELECT 1 FROM channels c JOIN memberships m ON m.room_id=c.room_id WHERE c.id=$1 AND m.user_id=$2 AND m.role IN ('owner','admin')", [req.params.channelId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" }); await client.query("BEGIN"); await client.query("DELETE FROM channel_access WHERE channel_id=$1", [req.params.channelId]); for (const userId of userIds) await client.query("INSERT INTO channel_access(channel_id,user_id) VALUES($1,$2)", [req.params.channelId, userId]); await client.query("COMMIT"); res.status(204).end(); } catch (error) { await client.query("ROLLBACK"); next(error); } finally { client.release(); } });

routes.get("/channels/:channelId/messages", async (req, res, next) => { try { const result = await query(`SELECT m.id,m.channel_id AS "channelId",coalesce(m.body,'') AS body,m.created_at AS "createdAt",json_build_object('id',u.id,'username',u.username,'displayName',u.display_name,'avatarUrl',CASE WHEN u.avatar_id IS NULL THEN NULL ELSE '/api/attachments/'||u.avatar_id END) AS author,CASE WHEN a.id IS NULL THEN NULL ELSE json_build_object('id',a.id,'filename',a.filename,'mimeType',a.mime_type,'sizeBytes',a.size_bytes,'url','/api/attachments/'||a.id) END AS attachment FROM messages m JOIN users u ON u.id=m.author_id LEFT JOIN attachments a ON a.id=m.attachment_id JOIN channels c ON c.id=m.channel_id JOIN memberships ms ON ms.room_id=c.room_id WHERE m.channel_id=$1 AND ms.user_id=$2 ORDER BY m.created_at DESC LIMIT 100`, [req.params.channelId, req.user!.id]); res.json(result.rows.reverse()); } catch (error) { next(error); } });
routes.post("/attachments", upload.single("file"), async (req, res, next) => { try { if (!req.file) return res.status(400).json({ error: "Arquivo ausente" }); const result = await query<any>("INSERT INTO attachments(uploaded_by,filename,mime_type,size_bytes,content) VALUES($1,$2,$3,$4,$5) RETURNING id,filename,mime_type AS \"mimeType\",size_bytes AS \"sizeBytes\"", [req.user!.id, req.file.originalname.slice(0, 255), req.file.mimetype, req.file.size, req.file.buffer]); res.status(201).json({ ...result.rows[0], url: `/api/attachments/${result.rows[0].id}` }); } catch (error) { next(error); } });

routes.post("/rooms/:roomId/invites", async (req, res, next) => { try { const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role IN ('owner','admin')", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" }); const code = randomBytes(12).toString("base64url"); const result = await query("INSERT INTO invites(room_id,code,created_by,expires_at,max_uses) VALUES($1,$2,$3,now()+interval '7 days',20) RETURNING code,expires_at AS \"expiresAt\"", [req.params.roomId, code, req.user!.id]); res.status(201).json(result.rows[0]); } catch (error) { next(error); } });
routes.post("/invites/:code/join", async (req, res, next) => { const client = await pool.connect(); try { await client.query("BEGIN"); const invite = (await client.query("SELECT * FROM invites WHERE code=$1 AND (expires_at IS NULL OR expires_at>now()) AND (max_uses IS NULL OR uses<max_uses) FOR UPDATE", [req.params.code])).rows[0]; if (!invite) { await client.query("ROLLBACK"); return res.status(404).json({ error: "Convite inválido ou expirado" }); } await client.query("INSERT INTO memberships(room_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING", [invite.room_id, req.user!.id]); await client.query("UPDATE invites SET uses=uses+1 WHERE id=$1", [invite.id]); await client.query("COMMIT"); res.json({ roomId: invite.room_id }); } catch (error) { await client.query("ROLLBACK"); next(error); } finally { client.release(); } });
routes.get("/rooms/:roomId/members", async (req, res, next) => { try { const result = await query(`SELECT u.id,u.username,u.display_name AS "displayName",u.real_name AS "realName",u.email,u.site_role AS "siteRole",m.role,CASE WHEN u.avatar_id IS NULL THEN NULL ELSE '/api/attachments/'||u.avatar_id END AS "avatarUrl",CASE WHEN u.banner_id IS NULL THEN NULL ELSE '/api/attachments/'||u.banner_id END AS "bannerUrl" FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.room_id=$1 AND ($3='superadmin' OR EXISTS(SELECT 1 FROM memberships mine WHERE mine.room_id=m.room_id AND mine.user_id=$2)) ORDER BY m.joined_at`, [req.params.roomId, req.user!.id, req.user!.siteRole ?? "user"]); res.json(result.rows); } catch (error) { next(error); } });
routes.patch("/rooms/:roomId/members/:userId", async (req, res, next) => { try { const role = z.object({ role: z.enum(["admin", "member"]) }).parse(req.body).role; const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role='owner'", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" }); await query("UPDATE memberships SET role=$1 WHERE room_id=$2 AND user_id=$3 AND role<>'owner'", [role, req.params.roomId, req.params.userId]); res.status(204).end(); } catch (error) { next(error); } });

routes.get("/users/search", async (req, res, next) => { try { const term = z.string().min(2).parse(req.query.q); const result = await query(`SELECT ${userSelect} FROM users WHERE id<>$1 AND username ILIKE $2 ORDER BY username LIMIT 10`, [req.user!.id, `%${term.replace(/^@/, "")}%`]); res.json(result.rows); } catch (error) { next(error); } });
routes.post("/friends/requests", async (req, res, next) => { try { const username = z.object({ username: z.string().min(3) }).parse(req.body).username.replace(/^@/, ""); const receiver = await query<{ id: string }>("SELECT id FROM users WHERE username=lower($1) AND id<>$2", [username, req.user!.id]); if (!receiver.rows[0]) return res.status(404).json({ error: "Usuário não encontrado" }); const result = await query("INSERT INTO friend_requests(sender_id,receiver_id) SELECT $1,$2 WHERE NOT EXISTS(SELECT 1 FROM friend_requests WHERE (sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1)) RETURNING id", [req.user!.id, receiver.rows[0].id]); if (!result.rowCount) return res.status(409).json({ error: "Já existe uma solicitação ou amizade" }); res.status(201).json({ ok: true }); } catch (error) { next(error); } });
routes.get("/friends/requests", async (req, res, next) => { try { const result = await query(`SELECT fr.id,fr.status,fr.created_at AS "createdAt",json_build_object('id',u.id,'username',u.username,'displayName',u.display_name,'realName',u.real_name) AS sender FROM friend_requests fr JOIN users u ON u.id=fr.sender_id WHERE fr.receiver_id=$1 AND fr.status='pending' ORDER BY fr.created_at DESC`, [req.user!.id]); res.json(result.rows); } catch (error) { next(error); } });
routes.patch("/friends/requests/:id", async (req, res, next) => { try { const status = z.object({ status: z.enum(["accepted", "rejected"]) }).parse(req.body).status; const result = await query("UPDATE friend_requests SET status=$1,updated_at=now() WHERE id=$2 AND receiver_id=$3 AND status='pending' RETURNING id", [status, req.params.id, req.user!.id]); if (!result.rowCount) return res.status(404).json({ error: "Solicitação não encontrada" }); res.json({ ok: true }); } catch (error) { next(error); } });
routes.get("/friends", async (req, res, next) => { try { const result = await query(`SELECT ${userSelect} FROM users WHERE id IN (SELECT CASE WHEN sender_id=$1 THEN receiver_id ELSE sender_id END FROM friend_requests WHERE status='accepted' AND (sender_id=$1 OR receiver_id=$1)) ORDER BY display_name`, [req.user!.id]); res.json(result.rows); } catch (error) { next(error); } });

routes.get("/preferences", async (req, res, next) => { try { const result = await query("SELECT theme FROM user_preferences WHERE user_id=$1", [req.user!.id]); res.json(result.rows[0]?.theme ?? { mode: "gradient", primary: "#7c5cff", secondary: "#22c5b5", surface: "#20232d" }); } catch (error) { next(error); } });
routes.put("/preferences", async (req, res, next) => { try { const theme = z.object({ mode: z.enum(["solid", "gradient"]), primary: z.string().regex(/^#[0-9a-f]{6}$/i), secondary: z.string().regex(/^#[0-9a-f]{6}$/i), surface: z.string().regex(/^#[0-9a-f]{6}$/i) }).parse(req.body); await query("INSERT INTO user_preferences(user_id,theme) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET theme=EXCLUDED.theme,updated_at=now()", [req.user!.id, JSON.stringify(theme)]); res.json(theme); } catch (error) { next(error); } });

routes.get("/admin/rooms", requireSiteAdmin, async (_req, res, next) => { try { const result = await query(`SELECT r.id,r.name,r.slug,r.created_by AS "createdBy",u.username AS owner,(SELECT count(*)::int FROM memberships m WHERE m.room_id=r.id) AS "memberCount",${roomMediaSelect} FROM rooms r JOIN users u ON u.id=r.created_by ORDER BY r.created_at DESC`); res.json(result.rows); } catch (error) { next(error); } });
routes.post("/admin/rooms/:roomId/join", requireSiteAdmin, async (req, res, next) => { try { await query("INSERT INTO memberships(room_id,user_id,role) VALUES($1,$2,'admin') ON CONFLICT(room_id,user_id) DO UPDATE SET role=CASE WHEN memberships.role='owner' THEN 'owner' ELSE 'admin' END", [req.params.roomId, req.user!.id]); res.json({ roomId: req.params.roomId }); } catch (error) { next(error); } });
