import { Router } from "express";
import bcrypt from "bcryptjs";
import multer from "multer";
import { randomBytes } from "node:crypto";
import { z } from "zod";
import { pool, query } from "./db.js";
import { requireAuth, requireSiteAdmin, signToken } from "./auth.js";
import { notifyMemberJoined } from "./socket.js";

export const routes = Router();
routes.get("/diagnostics/ping", (_request, response) => response.json({ ok: true, serverTime: Date.now() }));
routes.get("/diagnostics/download", (_request, response) => {
  response.setHeader("Content-Type", "application/octet-stream");
  response.setHeader("Cache-Control", "no-store");
  response.send(Buffer.alloc(512 * 1024, "friendcord-speed-test"));
});
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 8 * 1024 * 1024, files: 1 } });
routes.post("/diagnostics/upload", upload.single("file"), (request, response) => response.json({ bytes: request.file?.size ?? 0 }));
const userSelect = `id,username,display_name AS "displayName",real_name AS "realName",email,site_role AS "siteRole",custom_status AS "customStatus",CASE WHEN avatar_id IS NULL THEN NULL ELSE '/api/attachments/'||avatar_id END AS "avatarUrl",CASE WHEN banner_id IS NULL THEN NULL ELSE '/api/attachments/'||banner_id END AS "bannerUrl"`;
const roomMediaSelect = `CASE WHEN r.icon_id IS NULL THEN NULL ELSE '/api/attachments/'||r.icon_id END AS "iconUrl",CASE WHEN r.banner_id IS NULL THEN NULL ELSE '/api/attachments/'||r.banner_id END AS "bannerUrl"`;
type RolePermissions = Record<string, boolean>;
async function hasRoomPermission(roomId: string, userId: string, siteRole: string | undefined, permission: keyof RolePermissions) { if (siteRole === "superadmin") return true; const result = await query<{ allowed: boolean }>(`SELECT m.role='owner' OR coalesce((rp.permissions->>$3)::boolean,false) OR EXISTS(SELECT 1 FROM server_role_members srm JOIN server_roles sr ON sr.id=srm.role_id WHERE srm.user_id=m.user_id AND sr.room_id=m.room_id AND coalesce((sr.permissions->>$3)::boolean,false)) AS allowed FROM memberships m LEFT JOIN room_role_permissions rp ON rp.room_id=m.room_id AND rp.role=m.role WHERE m.room_id=$1 AND m.user_id=$2`, [roomId, userId, permission]); return !!result.rows[0]?.allowed; }

routes.get("/health", (_req, res) => res.json({ ok: true }));
routes.get("/attachments/:id", async (req, res, next) => { try {
  const result = await query<{ filename: string; mime_type: string; content: Buffer }>("SELECT filename,mime_type,content FROM attachments WHERE id=$1", [req.params.id]); const file = result.rows[0]; if (!file) return res.status(404).end();
  res.setHeader("Content-Type", file.mime_type); res.setHeader("Content-Disposition", `inline; filename*=UTF-8''${encodeURIComponent(file.filename)}`); res.setHeader("Cache-Control", "public, max-age=31536000, immutable"); res.send(file.content);
} catch (error) { next(error); } });

routes.post("/auth/register", async (req, res, next) => { try {
  const data = z.object({ username: z.string().regex(/^[a-zA-Z0-9_]{3,32}$/), password: z.string().min(8).max(100), displayName: z.string().min(2).max(50), realName: z.string().min(3).max(100), email: z.string().email().max(254) }).parse(req.body);
  const passwordHash = await bcrypt.hash(data.password, 12); const siteRole = data.username.toLowerCase() === "arcanjoraziel" && data.email.toLowerCase() === "azazjogos@gmail.com" ? "superadmin" : "user";
  const result = await query<any>(`INSERT INTO users(username,display_name,real_name,email,password_hash,site_role) VALUES(lower($1),$2,$3,lower($4),$5,$6) RETURNING ${userSelect}`, [data.username, data.displayName, data.realName, data.email, passwordHash, siteRole]); const user = result.rows[0]; res.status(201).json({ token: signToken(user), user });
} catch (error) { next(error); } });
routes.post("/auth/login", async (req, res, next) => { try {
  const data = z.object({ username: z.string().min(3), password: z.string().min(8).max(100) }).parse(req.body); const result = await query<any>(`SELECT ${userSelect},password_hash FROM users WHERE username=lower($1)`, [data.username]); const row = result.rows[0]; if (!row || !(await bcrypt.compare(data.password, row.password_hash))) return res.status(401).json({ error: "Usuário ou senha inválidos" }); delete row.password_hash; res.json({ token: signToken(row), user: row });
} catch (error) { next(error); } });

routes.use(requireAuth);
routes.get("/me", async (req, res, next) => { try { await query("UPDATE users SET site_role='superadmin',email='azazjogos@gmail.com' WHERE id=$1 AND lower(username)='arcanjoraziel'", [req.user!.id]); const result = await query(`SELECT ${userSelect} FROM users WHERE id=$1`, [req.user!.id]); res.json(result.rows[0]); } catch (error) { next(error); } });
routes.patch("/me", async (req, res, next) => { try {
  const data = z.object({ displayName: z.string().min(2).max(50).optional(), customStatus: z.string().max(120).optional(), avatarId: z.string().uuid().nullable().optional(), bannerId: z.string().uuid().nullable().optional() }).refine((value) => Object.keys(value).length > 0).parse(req.body);
  for (const attachmentId of [data.avatarId, data.bannerId]) if (attachmentId) { const image = await query("SELECT 1 FROM attachments WHERE id=$1 AND uploaded_by=$2 AND mime_type LIKE 'image/%'", [attachmentId, req.user!.id]); if (!image.rowCount) return res.status(400).json({ error: "Imagem inválida" }); }
  const result = await query<any>(`UPDATE users SET display_name=coalesce($1,display_name),custom_status=coalesce($2,custom_status),avatar_id=CASE WHEN $3::boolean THEN $4::uuid ELSE avatar_id END,banner_id=CASE WHEN $5::boolean THEN $6::uuid ELSE banner_id END WHERE id=$7 RETURNING ${userSelect}`,
    [data.displayName ?? null, data.customStatus ?? null, data.avatarId !== undefined, data.avatarId ?? null, data.bannerId !== undefined, data.bannerId ?? null, req.user!.id]);
  const user = result.rows[0]; res.json({ user, token: signToken(user) });
} catch (error) { next(error); } });
routes.get("/rooms", async (req, res, next) => { try { const result = await query(`SELECT r.id,r.name,r.slug,r.created_by AS "createdBy",m.role,${roomMediaSelect} FROM rooms r JOIN memberships m ON m.room_id=r.id WHERE m.user_id=$1 ORDER BY r.name`, [req.user!.id]); res.json(result.rows); } catch (error) { next(error); } });
routes.post("/rooms", async (req, res, next) => { const client = await pool.connect(); try {
  const data = z.object({ name: z.string().min(2).max(60) }).parse(req.body); const slug = `${data.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}-${randomBytes(3).toString("hex")}`;
  await client.query("BEGIN"); const room = (await client.query("INSERT INTO rooms(name,slug,created_by) VALUES($1,$2,$3) RETURNING id,name,slug,created_by AS \"createdBy\",NULL::text AS \"iconUrl\",NULL::text AS \"bannerUrl\"", [data.name, slug, req.user!.id])).rows[0]; await client.query("INSERT INTO memberships(room_id,user_id,role) VALUES($1,$2,'owner')", [room.id, req.user!.id]); const category = (await client.query("INSERT INTO channel_categories(room_id,name) VALUES($1,'Geral') RETURNING id", [room.id])).rows[0]; await client.query("INSERT INTO channels(room_id,name,kind,category_id) VALUES($1,'geral','text',$2),($1,'Geral','voice',$2)", [room.id, category.id]); await client.query("COMMIT"); res.status(201).json({ ...room, role: "owner" });
} catch (error) { await client.query("ROLLBACK"); next(error); } finally { client.release(); } });
routes.patch("/rooms/:roomId", async (req, res, next) => { try {
  const data = z.object({ name: z.string().min(2).max(60).optional(), iconId: z.string().uuid().nullable().optional(), bannerId: z.string().uuid().nullable().optional() }).refine((value) => Object.keys(value).length > 0).parse(req.body);
  const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role IN ('owner','admin')", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" });
  for (const attachmentId of [data.iconId, data.bannerId]) if (attachmentId) { const image = await query("SELECT 1 FROM attachments WHERE id=$1 AND uploaded_by=$2 AND mime_type LIKE 'image/%'", [attachmentId, req.user!.id]); if (!image.rowCount) return res.status(400).json({ error: "Imagem inválida" }); }
  const result = await query<any>(`UPDATE rooms r SET name=coalesce($1,name),icon_id=CASE WHEN $2::boolean THEN $3::uuid ELSE icon_id END,banner_id=CASE WHEN $4::boolean THEN $5::uuid ELSE banner_id END WHERE id=$6 RETURNING r.id,r.name,r.slug,r.created_by AS "createdBy",${roomMediaSelect}`,
    [data.name ?? null, data.iconId !== undefined, data.iconId ?? null, data.bannerId !== undefined, data.bannerId ?? null, req.params.roomId]); res.json(result.rows[0]);
} catch (error) { next(error); } });

routes.get("/rooms/:roomId/channels", async (req, res, next) => { try { const result = await query(`SELECT c.id,c.room_id AS "roomId",c.name,c.kind,c.category_id AS "categoryId",(EXISTS(SELECT 1 FROM channel_access ca WHERE ca.channel_id=c.id) OR EXISTS(SELECT 1 FROM channel_role_access cra WHERE cra.channel_id=c.id)) AS restricted FROM channels c JOIN memberships m ON m.room_id=c.room_id WHERE c.room_id=$1 AND m.user_id=$2 AND ($3='superadmin' OR m.role IN ('owner','admin') OR (NOT EXISTS(SELECT 1 FROM channel_access ca WHERE ca.channel_id=c.id) AND NOT EXISTS(SELECT 1 FROM channel_role_access cra WHERE cra.channel_id=c.id)) OR EXISTS(SELECT 1 FROM channel_access ca WHERE ca.channel_id=c.id AND ca.user_id=$2) OR EXISTS(SELECT 1 FROM channel_role_access cra JOIN server_role_members srm ON srm.role_id=cra.role_id WHERE cra.channel_id=c.id AND srm.user_id=$2)) ORDER BY c.created_at`, [req.params.roomId, req.user!.id, req.user!.siteRole ?? "user"]); res.json(result.rows); } catch (error) { next(error); } });
routes.post("/rooms/:roomId/channels", async (req, res, next) => { try {
  const data = z.object({ name: z.string().min(1).max(40), kind: z.enum(["text", "voice"]), categoryId: z.string().uuid().nullable().optional(), allowedUserIds: z.array(z.string().uuid()).optional(), allowedRoleIds: z.array(z.string().uuid()).optional() }).parse(req.body); const allowed = await hasRoomPermission(req.params.roomId, req.user!.id, req.user!.siteRole, "manageChannels"); if (!allowed) return res.status(403).json({ error: "Sem permissão para gerenciar canais" });
  const client = await pool.connect(); try { await client.query("BEGIN"); const channel = (await client.query("INSERT INTO channels(room_id,name,kind,category_id) VALUES($1,$2,$3,$4) RETURNING id,room_id AS \"roomId\",name,kind,category_id AS \"categoryId\"", [req.params.roomId, data.name, data.kind, data.categoryId ?? null])).rows[0]; for (const userId of data.allowedUserIds ?? []) await client.query("INSERT INTO channel_access(channel_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING", [channel.id, userId]); for (const roleId of data.allowedRoleIds ?? []) await client.query("INSERT INTO channel_role_access(channel_id,role_id) SELECT $1,id FROM server_roles WHERE id=$2 AND room_id=$3 ON CONFLICT DO NOTHING", [channel.id, roleId, req.params.roomId]); await client.query("COMMIT"); res.status(201).json({ ...channel, restricted: !!((data.allowedUserIds?.length ?? 0) + (data.allowedRoleIds?.length ?? 0)) }); } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
} catch (error) { next(error); } });
routes.get("/channels/:channelId/access", async (req, res, next) => { try { const [users,roles] = await Promise.all([query<{userId:string}>("SELECT user_id AS \"userId\" FROM channel_access WHERE channel_id=$1", [req.params.channelId]),query<{roleId:string}>("SELECT role_id AS \"roleId\" FROM channel_role_access WHERE channel_id=$1", [req.params.channelId])]); res.json({ userIds:users.rows.map((row) => row.userId), roleIds:roles.rows.map((row) => row.roleId) }); } catch (error) { next(error); } });
routes.put("/channels/:channelId/access", async (req, res, next) => { const client = await pool.connect(); try { const data = z.object({ userIds: z.array(z.string().uuid()), roleIds: z.array(z.string().uuid()).default([]) }).parse(req.body); const allowed = req.user!.siteRole === "superadmin" || !!(await client.query("SELECT 1 FROM channels c JOIN memberships m ON m.room_id=c.room_id WHERE c.id=$1 AND m.user_id=$2 AND m.role IN ('owner','admin')", [req.params.channelId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" }); await client.query("BEGIN"); await client.query("DELETE FROM channel_access WHERE channel_id=$1", [req.params.channelId]); await client.query("DELETE FROM channel_role_access WHERE channel_id=$1", [req.params.channelId]); for (const userId of data.userIds) await client.query("INSERT INTO channel_access(channel_id,user_id) VALUES($1,$2)", [req.params.channelId, userId]); for (const roleId of data.roleIds) await client.query("INSERT INTO channel_role_access(channel_id,role_id) SELECT $1,sr.id FROM server_roles sr JOIN channels c ON c.room_id=sr.room_id WHERE sr.id=$2 AND c.id=$1", [req.params.channelId, roleId]); await client.query("COMMIT"); res.status(204).end(); } catch (error) { await client.query("ROLLBACK"); next(error); } finally { client.release(); } });

routes.get("/channels/:channelId/messages", async (req, res, next) => { try { const result = await query(`SELECT m.id,m.channel_id AS "channelId",coalesce(m.body,'') AS body,m.created_at AS "createdAt",json_build_object('id',u.id,'username',u.username,'displayName',u.display_name,'avatarUrl',CASE WHEN u.avatar_id IS NULL THEN NULL ELSE '/api/attachments/'||u.avatar_id END) AS author,CASE WHEN a.id IS NULL THEN NULL ELSE json_build_object('id',a.id,'filename',a.filename,'mimeType',a.mime_type,'sizeBytes',a.size_bytes,'url','/api/attachments/'||a.id) END AS attachment FROM messages m JOIN users u ON u.id=m.author_id LEFT JOIN attachments a ON a.id=m.attachment_id JOIN channels c ON c.id=m.channel_id JOIN memberships ms ON ms.room_id=c.room_id WHERE m.channel_id=$1 AND ms.user_id=$2 ORDER BY m.created_at DESC LIMIT 100`, [req.params.channelId, req.user!.id]); res.json(result.rows.reverse()); } catch (error) { next(error); } });
routes.post("/attachments", upload.single("file"), async (req, res, next) => { try { if (!req.file) return res.status(400).json({ error: "Arquivo ausente" }); const result = await query<any>("INSERT INTO attachments(uploaded_by,filename,mime_type,size_bytes,content) VALUES($1,$2,$3,$4,$5) RETURNING id,filename,mime_type AS \"mimeType\",size_bytes AS \"sizeBytes\"", [req.user!.id, req.file.originalname.slice(0, 255), req.file.mimetype, req.file.size, req.file.buffer]); res.status(201).json({ ...result.rows[0], url: `/api/attachments/${result.rows[0].id}` }); } catch (error) { next(error); } });

routes.post("/rooms/:roomId/invites", async (req, res, next) => { try { const allowed = await hasRoomPermission(req.params.roomId, req.user!.id, req.user!.siteRole, "createInvites"); if (!allowed) return res.status(403).json({ error: "Sem permissão para criar convites" }); const code = randomBytes(12).toString("base64url"); const result = await query("INSERT INTO invites(room_id,code,created_by,expires_at,max_uses) VALUES($1,$2,$3,now()+interval '7 days',20) RETURNING code,expires_at AS \"expiresAt\"", [req.params.roomId, code, req.user!.id]); res.status(201).json(result.rows[0]); } catch (error) { next(error); } });
routes.post("/invites/:code/join", async (req, res, next) => { const client = await pool.connect(); try { await client.query("BEGIN"); const invite = (await client.query("SELECT * FROM invites WHERE code=$1 AND (expires_at IS NULL OR expires_at>now()) AND (max_uses IS NULL OR uses<max_uses) FOR UPDATE", [req.params.code])).rows[0]; if (!invite) { await client.query("ROLLBACK"); return res.status(404).json({ error: "Convite inválido ou expirado" }); } const joined = await client.query("INSERT INTO memberships(room_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING user_id", [invite.room_id, req.user!.id]); await client.query("UPDATE invites SET uses=uses+1 WHERE id=$1", [invite.id]); await client.query("COMMIT"); if (joined.rowCount) await notifyMemberJoined(invite.room_id, req.user!.id); res.json({ roomId: invite.room_id }); } catch (error) { await client.query("ROLLBACK"); next(error); } finally { client.release(); } });
routes.get("/rooms/:roomId/members", async (req, res, next) => { try { const result = await query(`SELECT u.id,u.username,u.display_name AS "displayName",u.real_name AS "realName",u.email,u.site_role AS "siteRole",m.role,CASE WHEN u.avatar_id IS NULL THEN NULL ELSE '/api/attachments/'||u.avatar_id END AS "avatarUrl",CASE WHEN u.banner_id IS NULL THEN NULL ELSE '/api/attachments/'||u.banner_id END AS "bannerUrl" FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.room_id=$1 AND ($3='superadmin' OR EXISTS(SELECT 1 FROM memberships mine WHERE mine.room_id=m.room_id AND mine.user_id=$2)) ORDER BY m.joined_at`, [req.params.roomId, req.user!.id, req.user!.siteRole ?? "user"]); res.json(result.rows); } catch (error) { next(error); } });
routes.patch("/rooms/:roomId/members/:userId", async (req, res, next) => { try { const role = z.object({ role: z.enum(["admin", "member"]) }).parse(req.body).role; const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role='owner'", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" }); await query("UPDATE memberships SET role=$1 WHERE room_id=$2 AND user_id=$3 AND role<>'owner'", [role, req.params.roomId, req.params.userId]); res.status(204).end(); } catch (error) { next(error); } });

routes.get("/users/search", async (req, res, next) => { try { const term = z.string().min(2).parse(req.query.q); const result = await query(`SELECT ${userSelect} FROM users WHERE id<>$1 AND username ILIKE $2 ORDER BY username LIMIT 10`, [req.user!.id, `%${term.replace(/^@/, "")}%`]); res.json(result.rows); } catch (error) { next(error); } });
routes.post("/friends/requests", async (req, res, next) => { try { const username = z.object({ username: z.string().min(3) }).parse(req.body).username.replace(/^@/, ""); const receiver = await query<{ id: string }>("SELECT id FROM users WHERE username=lower($1) AND id<>$2", [username, req.user!.id]); if (!receiver.rows[0]) return res.status(404).json({ error: "Usuário não encontrado" }); const result = await query("INSERT INTO friend_requests(sender_id,receiver_id) SELECT $1,$2 WHERE NOT EXISTS(SELECT 1 FROM friend_requests WHERE (sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1)) RETURNING id", [req.user!.id, receiver.rows[0].id]); if (!result.rowCount) return res.status(409).json({ error: "Já existe uma solicitação ou amizade" }); res.status(201).json({ ok: true }); } catch (error) { next(error); } });
routes.get("/friends/requests", async (req, res, next) => { try { const result = await query(`SELECT fr.id,fr.status,fr.created_at AS "createdAt",json_build_object('id',u.id,'username',u.username,'displayName',u.display_name,'realName',u.real_name) AS sender FROM friend_requests fr JOIN users u ON u.id=fr.sender_id WHERE fr.receiver_id=$1 AND fr.status='pending' ORDER BY fr.created_at DESC`, [req.user!.id]); res.json(result.rows); } catch (error) { next(error); } });
routes.patch("/friends/requests/:id", async (req, res, next) => { try { const status = z.object({ status: z.enum(["accepted", "rejected"]) }).parse(req.body).status; const result = await query("UPDATE friend_requests SET status=$1,updated_at=now() WHERE id=$2 AND receiver_id=$3 AND status='pending' RETURNING id", [status, req.params.id, req.user!.id]); if (!result.rowCount) return res.status(404).json({ error: "Solicitação não encontrada" }); res.json({ ok: true }); } catch (error) { next(error); } });
routes.get("/friends", async (req, res, next) => { try { const result = await query(`SELECT ${userSelect} FROM users WHERE id IN (SELECT CASE WHEN sender_id=$1 THEN receiver_id ELSE sender_id END FROM friend_requests WHERE status='accepted' AND (sender_id=$1 OR receiver_id=$1)) ORDER BY display_name`, [req.user!.id]); res.json(result.rows); } catch (error) { next(error); } });
routes.get("/message-requests", async (req, res, next) => { try { const result = await query(`SELECT mr.id,mr.created_at AS "createdAt",json_build_object('id',u.id,'username',u.username,'displayName',u.display_name,'customStatus',u.custom_status,'avatarUrl',CASE WHEN u.avatar_id IS NULL THEN NULL ELSE '/api/attachments/'||u.avatar_id END,'bannerUrl',CASE WHEN u.banner_id IS NULL THEN NULL ELSE '/api/attachments/'||u.banner_id END) AS sender,coalesce((SELECT body FROM direct_messages WHERE sender_id=mr.sender_id AND receiver_id=mr.receiver_id ORDER BY created_at DESC LIMIT 1),'Mensagem ou arquivo') AS preview FROM message_requests mr JOIN users u ON u.id=mr.sender_id WHERE mr.receiver_id=$1 AND mr.status='pending' ORDER BY mr.created_at DESC`, [req.user!.id]); res.json(result.rows); } catch (error) { next(error); } });
routes.patch("/message-requests/:id", async (req, res, next) => { try { const status=z.object({status:z.enum(["accepted","rejected"])}).parse(req.body).status; const result=await query<any>("UPDATE message_requests SET status=$1,updated_at=now() WHERE id=$2 AND receiver_id=$3 AND status='pending' RETURNING sender_id AS \"senderId\"",[status,req.params.id,req.user!.id]); if(!result.rowCount)return res.status(404).json({error:"Solicitação não encontrada"}); res.json({ok:true,senderId:result.rows[0].senderId}); } catch(error){next(error);} });

routes.get("/dms/:userId/messages", async (req, res, next) => { try {
  const friend = await query("SELECT 1 WHERE EXISTS(SELECT 1 FROM friend_requests WHERE status='accepted' AND ((sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1))) OR EXISTS(SELECT 1 FROM message_requests WHERE (status='accepted' OR (status='pending' AND sender_id=$1 AND receiver_id=$2)) AND ((sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1)))", [req.user!.id, req.params.userId]);
  if (!friend.rowCount) return res.status(403).json({ error: "Esta conversa ainda aguarda aceitação" });
  const result = await query(`SELECT dm.id,dm.sender_id AS "senderId",dm.receiver_id AS "receiverId",coalesce(dm.body,'') AS body,dm.created_at AS "createdAt",json_build_object('id',u.id,'username',u.username,'displayName',u.display_name,'customStatus',u.custom_status,'avatarUrl',CASE WHEN u.avatar_id IS NULL THEN NULL ELSE '/api/attachments/'||u.avatar_id END) AS author,CASE WHEN a.id IS NULL THEN NULL ELSE json_build_object('id',a.id,'filename',a.filename,'mimeType',a.mime_type,'sizeBytes',a.size_bytes,'url','/api/attachments/'||a.id) END AS attachment FROM direct_messages dm JOIN users u ON u.id=dm.sender_id LEFT JOIN attachments a ON a.id=dm.attachment_id WHERE (dm.sender_id=$1 AND dm.receiver_id=$2) OR (dm.sender_id=$2 AND dm.receiver_id=$1) OR (dm.receiver_id=$1 AND dm.context_peer_id=$2) ORDER BY dm.created_at DESC LIMIT 100`, [req.user!.id, req.params.userId]);
  res.json(result.rows.reverse());
} catch (error) { next(error); } });

routes.get("/rooms/:roomId/permissions", async (req, res, next) => { try {
  const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role IN ('owner','admin')", [req.params.roomId, req.user!.id])).rowCount;
  if (!allowed) return res.status(403).json({ error: "Sem permissão" });
  const result = await query("SELECT role,permissions FROM room_role_permissions WHERE room_id=$1 ORDER BY role", [req.params.roomId]); res.json(result.rows);
} catch (error) { next(error); } });
routes.put("/rooms/:roomId/permissions", async (req, res, next) => { try {
  const data = z.object({ role: z.enum(["admin", "member"]), permissions: z.record(z.string(), z.boolean()) }).parse(req.body);
  const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role='owner'", [req.params.roomId, req.user!.id])).rowCount;
  if (!allowed) return res.status(403).json({ error: "Somente o dono ou admin global pode alterar cargos" });
  await query("INSERT INTO room_role_permissions(room_id,role,permissions) VALUES($1,$2,$3) ON CONFLICT(room_id,role) DO UPDATE SET permissions=EXCLUDED.permissions,updated_at=now()", [req.params.roomId, data.role, JSON.stringify(data.permissions)]); res.json(data);
} catch (error) { next(error); } });

const permissionMap = z.record(z.string(), z.boolean());
routes.get("/rooms/:roomId/categories", async (req, res, next) => { try {
  const result = await query(`SELECT cc.id,cc.room_id AS "roomId",cc.name,cc.position FROM channel_categories cc WHERE cc.room_id=$1 AND ($3='superadmin' OR EXISTS(SELECT 1 FROM memberships WHERE room_id=cc.room_id AND user_id=$2)) ORDER BY cc.position,cc.created_at`, [req.params.roomId, req.user!.id, req.user!.siteRole ?? "user"]); res.json(result.rows);
} catch (error) { next(error); } });
routes.post("/rooms/:roomId/categories", async (req, res, next) => { try {
  const allowed = await hasRoomPermission(req.params.roomId, req.user!.id, req.user!.siteRole, "manageChannels"); if (!allowed) return res.status(403).json({ error: "Sem permissão para criar categorias" }); const data = z.object({ name: z.string().min(1).max(60) }).parse(req.body); const result = await query(`INSERT INTO channel_categories(room_id,name,position) VALUES($1,$2,(SELECT coalesce(max(position),-1)+1 FROM channel_categories WHERE room_id=$1)) RETURNING id,room_id AS "roomId",name,position`, [req.params.roomId, data.name]); res.status(201).json(result.rows[0]);
} catch (error) { next(error); } });
routes.get("/rooms/:roomId/custom-roles", async (req, res, next) => { try {
  const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Sem permissão" });
  const result = await query(`SELECT sr.id,sr.room_id AS "roomId",sr.name,sr.color,sr.permissions,coalesce((SELECT json_agg(srm.user_id) FROM server_role_members srm WHERE srm.role_id=sr.id),'[]') AS "memberIds",coalesce((SELECT json_object_agg(crp.category_id,crp.permissions) FROM category_role_permissions crp WHERE crp.role_id=sr.id),'{}') AS "categoryPermissions" FROM server_roles sr WHERE sr.room_id=$1 ORDER BY sr.position,sr.created_at`, [req.params.roomId]); res.json(result.rows);
} catch (error) { next(error); } });
routes.post("/rooms/:roomId/custom-roles", async (req, res, next) => { const client = await pool.connect(); try {
  const allowed = req.user!.siteRole === "superadmin" || !!(await client.query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role='owner'", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Somente o dono pode criar cargos" }); const data = z.object({ name: z.string().min(1).max(40), color: z.string().regex(/^#[0-9a-f]{6}$/i), permissions: permissionMap, memberIds: z.array(z.string().uuid()), categoryPermissions: z.record(z.string().uuid(), permissionMap) }).parse(req.body); await client.query("BEGIN"); const role = (await client.query(`INSERT INTO server_roles(room_id,name,color,permissions,position) VALUES($1,$2,$3,$4,(SELECT coalesce(max(position),-1)+1 FROM server_roles WHERE room_id=$1)) RETURNING id,room_id AS "roomId",name,color,permissions`, [req.params.roomId,data.name,data.color,JSON.stringify(data.permissions)])).rows[0]; for (const userId of data.memberIds) await client.query("INSERT INTO server_role_members(role_id,user_id) VALUES($1,$2)", [role.id,userId]); for (const [categoryId,permissions] of Object.entries(data.categoryPermissions)) await client.query("INSERT INTO category_role_permissions(category_id,role_id,permissions) VALUES($1,$2,$3)", [categoryId,role.id,JSON.stringify(permissions)]); await client.query("COMMIT"); res.status(201).json({ ...role, memberIds:data.memberIds, categoryPermissions:data.categoryPermissions });
} catch (error) { await client.query("ROLLBACK"); next(error); } finally { client.release(); } });
routes.put("/rooms/:roomId/custom-roles/:roleId", async (req, res, next) => { const client = await pool.connect(); try {
  const allowed = req.user!.siteRole === "superadmin" || !!(await client.query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role='owner'", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Somente o dono pode editar cargos" }); const data = z.object({ name: z.string().min(1).max(40), color: z.string().regex(/^#[0-9a-f]{6}$/i), permissions: permissionMap, memberIds: z.array(z.string().uuid()), categoryPermissions: z.record(z.string().uuid(), permissionMap) }).parse(req.body); await client.query("BEGIN"); await client.query("UPDATE server_roles SET name=$1,color=$2,permissions=$3 WHERE id=$4 AND room_id=$5", [data.name,data.color,JSON.stringify(data.permissions),req.params.roleId,req.params.roomId]); await client.query("DELETE FROM server_role_members WHERE role_id=$1", [req.params.roleId]); for (const userId of data.memberIds) await client.query("INSERT INTO server_role_members(role_id,user_id) VALUES($1,$2)", [req.params.roleId,userId]); await client.query("DELETE FROM category_role_permissions WHERE role_id=$1", [req.params.roleId]); for (const [categoryId,permissions] of Object.entries(data.categoryPermissions)) await client.query("INSERT INTO category_role_permissions(category_id,role_id,permissions) VALUES($1,$2,$3)", [categoryId,req.params.roleId,JSON.stringify(permissions)]); await client.query("COMMIT"); res.json(data);
} catch (error) { await client.query("ROLLBACK"); next(error); } finally { client.release(); } });
routes.delete("/rooms/:roomId/custom-roles/:roleId", async (req, res, next) => { try { const allowed = req.user!.siteRole === "superadmin" || !!(await query("SELECT 1 FROM memberships WHERE room_id=$1 AND user_id=$2 AND role='owner'", [req.params.roomId, req.user!.id])).rowCount; if (!allowed) return res.status(403).json({ error: "Somente o dono pode remover cargos" }); await query("DELETE FROM server_roles WHERE id=$1 AND room_id=$2", [req.params.roleId,req.params.roomId]); res.status(204).end(); } catch (error) { next(error); } });

routes.get("/preferences", async (req, res, next) => { try { const result = await query("SELECT theme FROM user_preferences WHERE user_id=$1", [req.user!.id]); res.json(result.rows[0]?.theme ?? { mode: "gradient", primary: "#7c5cff", secondary: "#22c5b5", surface: "#20232d" }); } catch (error) { next(error); } });
routes.put("/preferences", async (req, res, next) => { try { const theme = z.object({ mode: z.enum(["solid", "gradient"]), primary: z.string().regex(/^#[0-9a-f]{6}$/i), secondary: z.string().regex(/^#[0-9a-f]{6}$/i), surface: z.string().regex(/^#[0-9a-f]{6}$/i) }).parse(req.body); await query("INSERT INTO user_preferences(user_id,theme) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET theme=EXCLUDED.theme,updated_at=now()", [req.user!.id, JSON.stringify(theme)]); res.json(theme); } catch (error) { next(error); } });
routes.get("/rooms/:roomId/notification-preference", async (req,res,next)=>{try{const result=await query<{muted:boolean}>("SELECT muted FROM room_notification_preferences WHERE room_id=$1 AND user_id=$2",[req.params.roomId,req.user!.id]);res.json({muted:result.rows[0]?.muted??false});}catch(error){next(error);}});
routes.put("/rooms/:roomId/notification-preference", async (req,res,next)=>{try{const muted=z.object({muted:z.boolean()}).parse(req.body).muted;await query("INSERT INTO room_notification_preferences(room_id,user_id,muted) VALUES($1,$2,$3) ON CONFLICT(room_id,user_id) DO UPDATE SET muted=EXCLUDED.muted,updated_at=now()",[req.params.roomId,req.user!.id,muted]);res.json({muted});}catch(error){next(error);}});

routes.get("/admin/rooms", requireSiteAdmin, async (_req, res, next) => { try { const result = await query(`SELECT r.id,r.name,r.slug,r.created_by AS "createdBy",coalesce(u.username,'usuário removido') AS owner,(SELECT count(*)::int FROM memberships m WHERE m.room_id=r.id) AS "memberCount",${roomMediaSelect} FROM rooms r LEFT JOIN users u ON u.id=r.created_by ORDER BY r.created_at DESC`); res.json(result.rows); } catch (error) { next(error); } });
routes.post("/admin/rooms/:roomId/join", requireSiteAdmin, async (req, res, next) => { try { await query("INSERT INTO memberships(room_id,user_id,role) VALUES($1,$2,'admin') ON CONFLICT(room_id,user_id) DO UPDATE SET role=CASE WHEN memberships.role='owner' THEN 'owner' ELSE 'admin' END", [req.params.roomId, req.user!.id]); res.json({ roomId: req.params.roomId }); } catch (error) { next(error); } });
routes.get("/admin/users", requireSiteAdmin, async (req, res, next) => { try { const search = z.string().trim().max(32).optional().parse(req.query.q)?.replace(/^@/, "").toLowerCase(); const result = search ? await query(`SELECT ${userSelect} FROM users WHERE username ILIKE $1 ORDER BY username LIMIT 8`, [`%${search}%`]) : await query(`SELECT ${userSelect} FROM users WHERE site_role='superadmin' ORDER BY username`); res.json(result.rows); } catch (error) { next(error); } });
routes.patch("/admin/users/:userId/role", requireSiteAdmin, async (req, res, next) => { try { const siteRole = z.object({ siteRole: z.enum(["user", "superadmin"]) }).parse(req.body).siteRole; if (req.params.userId === req.user!.id && siteRole === "user") return res.status(400).json({ error: "Você não pode remover sua própria administração" }); await query("UPDATE users SET site_role=$1 WHERE id=$2", [siteRole, req.params.userId]); res.json({ ok: true }); } catch (error) { next(error); } });
