ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_id UUID REFERENCES attachments(id) ON DELETE SET NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_id UUID REFERENCES attachments(id) ON DELETE SET NULL;

ALTER TABLE rooms ADD COLUMN IF NOT EXISTS icon_id UUID REFERENCES attachments(id) ON DELETE SET NULL;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS banner_id UUID REFERENCES attachments(id) ON DELETE SET NULL;
