import { useEffect, useRef, useState } from "react";
import type { Attachment, Channel, ChatMessage, PublicUser, Room } from "@friendcord/shared";
import { API_URL, api, getToken, uploadFile } from "./api";
import { getSocket, resetSocket } from "./socket";
import { useWebRTC } from "./hooks/useWebRTC";
import { VideoTile } from "./components/VideoTile";
import { MediaRoom } from "./components/MediaRoom";

type RoomWithRole = Room & { role: "owner" | "admin" | "member" };
type View = "servers" | "friends" | "requests" | "themes" | "admin" | "room";
type Theme = { mode: "solid" | "gradient"; primary: string; secondary: string; surface: string };
type FriendRequest = { id: string; sender: PublicUser; createdAt: string };
type AdminRoom = Room & { owner: string; memberCount: number };

function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) {
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="modal"><header><h2>{title}</h2><button onClick={onClose}>×</button></header>{children}</section></div>;
}

const mediaUrl = (path?: string | null) => path ? `${API_URL}${path}` : "";
function Avatar({ person, size = "normal" }: { person: Pick<PublicUser, "displayName" | "avatarUrl">; size?: "normal" | "large" }) {
  return <div className={`avatar ${size === "large" ? "avatar-large" : ""}`}>{person.avatarUrl ? <img src={mediaUrl(person.avatarUrl)} alt=""/> : person.displayName.slice(0, 1).toUpperCase()}</div>;
}
function friendlyPermission(error: unknown) { const cause = error as DOMException; return cause?.name === "NotAllowedError" ? "Permissão de microfone, câmera ou tela recusada. Libere o acesso no cadeado do navegador e tente novamente." : cause?.message || "Não foi possível acessar o dispositivo."; }

function Auth({ onDone }: { onDone: (user: PublicUser) => void }) {
  const [register, setRegister] = useState(false); const [form, setForm] = useState({ displayName: "", realName: "", email: "", username: "", password: "" }); const [error, setError] = useState("");
  const field = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: event.target.value });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); try { const data = await api<{ token: string; user: PublicUser }>(`/auth/${register ? "register" : "login"}`, { method: "POST", body: JSON.stringify(form) }); localStorage.setItem("friendcord_token", data.token); onDone(data.user); } catch (cause) { setError((cause as Error).message); } };
  return <main className="auth"><form onSubmit={submit}><div className="auth-logo">F</div><h1>FriendCord</h1><p>Seu espaço privado para conversar e criar.</p>{register && <><label>Nome real<input value={form.realName} onChange={field("realName")} required/></label><label>Nome exibido<input value={form.displayName} onChange={field("displayName")} required/></label><label>E-mail<input type="email" value={form.email} onChange={field("email")} required/></label></>}<label>Usuário<input value={form.username} onChange={field("username")} minLength={3} required/></label><label>Senha<input type="password" value={form.password} onChange={field("password")} minLength={8} required/></label>{error && <div className="error">{error}</div>}<button className="primary" type="submit">{register ? "Criar minha conta" : "Entrar"}</button><button className="link" type="button" onClick={() => { setRegister(!register); setError(""); }}>{register ? "Já tenho uma conta" : "Ainda não tenho conta"}</button></form></main>;
}

function MessageText({ body }: { body: string }) {
  return <div className="message-body">{body.split("```").map((part, index) => index % 2 ? <pre key={index}><code>{part.replace(/^\w+\n/, "")}</code></pre> : <span key={index}>{part}</span>)}</div>;
}

function AttachmentView({ file }: { file: Attachment }) {
  const source = `${API_URL}${file.url}`;
  if (file.mimeType.startsWith("audio/")) return <audio className="audio-message" controls src={source}/>;
  if (file.mimeType.startsWith("image/")) return <a href={source} target="_blank"><img className="image-attachment" src={source} alt={file.filename}/></a>;
  return <a className="file-attachment" href={source} target="_blank" download>📎 <span>{file.filename}</span><small>{Math.ceil(file.sizeBytes / 1024)} KB</small></a>;
}

export default function App() {
  const [user, setUser] = useState<PublicUser | null>(null); const [view, setView] = useState<View>("servers"); const [rooms, setRooms] = useState<RoomWithRole[]>([]); const [roomId, setRoomId] = useState(""); const [channels, setChannels] = useState<Channel[]>([]); const [channelId, setChannelId] = useState(""); const [members, setMembers] = useState<PublicUser[]>([]); const [messages, setMessages] = useState<ChatMessage[]>([]); const [online, setOnline] = useState<PublicUser[]>([]); const [friends, setFriends] = useState<PublicUser[]>([]); const [requests, setRequests] = useState<FriendRequest[]>([]); const [adminRooms, setAdminRooms] = useState<AdminRoom[]>([]);
  const [body, setBody] = useState(""); const [error, setError] = useState(""); const [modal, setModal] = useState<"server" | "invite" | "inviteLink" | "channel" | "access" | "profile" | "serverSettings" | null>(null); const [serverName, setServerName] = useState(""); const [inviteCode, setInviteCode] = useState(""); const [inviteLink, setInviteLink] = useState(""); const [friendName, setFriendName] = useState(""); const [channelForm, setChannelForm] = useState({ name: "", kind: "text" as "text" | "voice", restricted: false, allowedUserIds: [] as string[] }); const [pendingFile, setPendingFile] = useState<File | null>(null); const [recording, setRecording] = useState(false); const [showTools, setShowTools] = useState(false); const [showMedia, setShowMedia] = useState(false); const [quality, setQuality] = useState("1920x1080x30"); const [volume, setVolume] = useState(1);
  const [devices, setDevices] = useState<MediaDeviceInfo[]>([]); const [audioInputId, setAudioInputId] = useState(localStorage.getItem("friendcord_audio_input") ?? ""); const [audioOutputId, setAudioOutputId] = useState(localStorage.getItem("friendcord_audio_output") ?? ""); const [cameraId, setCameraId] = useState(localStorage.getItem("friendcord_camera") ?? "");
  const [profileForm, setProfileForm] = useState({ username: "", displayName: "", avatar: null as File | null, banner: null as File | null }); const [serverForm, setServerForm] = useState({ name: "", icon: null as File | null, banner: null as File | null });
  const [theme, setTheme] = useState<Theme>({ mode: "gradient", primary: "#7c5cff", secondary: "#22c5b5", surface: "#20232d" });
  const fileInput = useRef<HTMLInputElement>(null); const textInput = useRef<HTMLTextAreaElement>(null); const audioRecorder = useRef<MediaRecorder | null>(null); const audioChunks = useRef<Blob[]>([]); const callRecorder = useRef<MediaRecorder | null>(null); const callChunks = useRef<Blob[]>([]); const rtc = useWebRTC();
  const currentRoom = rooms.find((room) => room.id === roomId); const currentChannel = channels.find((channel) => channel.id === channelId); const canManage = user?.siteRole === "superadmin" || currentRoom?.role === "owner" || currentRoom?.role === "admin";
  const applyTheme = (next: Theme) => { setTheme(next); const root = document.documentElement; root.style.setProperty("--primary", next.primary); root.style.setProperty("--secondary", next.secondary); root.style.setProperty("--surface", next.surface); root.style.setProperty("--accent-bg", next.mode === "gradient" ? `linear-gradient(135deg, ${next.primary}, ${next.secondary})` : next.primary); };
  const loadRooms = () => api<RoomWithRole[]>("/rooms").then(setRooms);
  const loadSocial = () => { api<PublicUser[]>("/friends").then(setFriends); api<FriendRequest[]>("/friends/requests").then(setRequests); };

  useEffect(() => { if (getToken()) api<PublicUser>("/me").then(setUser).catch(() => localStorage.removeItem("friendcord_token")); }, []);
  useEffect(() => { if (!user) return; loadRooms(); loadSocial(); api<Theme>("/preferences").then(applyTheme); const socket = getSocket(); const presence = (items: PublicUser[]) => setOnline(items); socket.on("presence:update", presence); socket.connect(); return () => { socket.off("presence:update", presence); }; }, [user]);
  useEffect(() => { if (view === "admin" && user?.siteRole === "superadmin") api<AdminRoom[]>("/admin/rooms").then(setAdminRooms); }, [view, user]);
  useEffect(() => { if (!roomId || view !== "room") return; Promise.all([api<Channel[]>(`/rooms/${roomId}/channels`), api<PublicUser[]>(`/rooms/${roomId}/members`)]).then(([nextChannels, nextMembers]) => { setChannels(nextChannels); setMembers(nextMembers); const first = nextChannels.find((item) => item.kind === "text"); setChannelId(first?.id ?? ""); }); }, [roomId, view]);
  useEffect(() => { if (!channelId || currentChannel?.kind !== "text") return; api<ChatMessage[]>(`/channels/${channelId}/messages`).then(setMessages); const socket = getSocket(); socket.emit("channel:join", channelId); const receive = (item: ChatMessage) => { if (item.channelId === channelId) setMessages((current) => [...current, item]); if (item.author.id !== user?.id && document.hidden && Notification.permission === "granted") new Notification(item.author.displayName, { body: item.body || "Enviou um arquivo" }); }; socket.on("message:new", receive); return () => { socket.off("message:new", receive); }; }, [channelId, currentChannel?.kind, user?.id]);

  if (!user) return <Auth onDone={setUser}/>;
  const openRoom = (id: string) => { rtc.leave(); setRoomId(id); setView("room"); };
  const createServer = async (event: React.FormEvent) => { event.preventDefault(); try { const room = await api<RoomWithRole>("/rooms", { method: "POST", body: JSON.stringify({ name: serverName }) }); setRooms([...rooms, room]); setModal(null); setServerName(""); openRoom(room.id); } catch (cause) { setError((cause as Error).message); } };
  const joinServer = async (event: React.FormEvent) => { event.preventDefault(); try { const code = inviteCode.split("invite=").pop()!; const result = await api<{ roomId: string }>(`/invites/${code}/join`, { method: "POST" }); await loadRooms(); setModal(null); openRoom(result.roomId); } catch (cause) { setError((cause as Error).message); } };
  const createInvite = async () => { try { const result = await api<{ code: string }>(`/rooms/${roomId}/invites`, { method: "POST" }); setInviteLink(`${location.origin}?invite=${result.code}`); setModal("inviteLink"); } catch (cause) { setError((cause as Error).message); } };
  const createChannel = async (event: React.FormEvent) => { event.preventDefault(); try { const channel = await api<Channel>(`/rooms/${roomId}/channels`, { method: "POST", body: JSON.stringify({ ...channelForm, allowedUserIds: channelForm.restricted ? channelForm.allowedUserIds : [] }) }); setChannels([...channels, channel]); setModal(null); setChannelForm({ name: "", kind: "text", restricted: false, allowedUserIds: [] }); } catch (cause) { setError((cause as Error).message); } };
  const saveAccess = async () => { try { await api(`/channels/${channelId}/access`, { method: "PUT", body: JSON.stringify({ userIds: channelForm.allowedUserIds }) }); setChannels(channels.map((item) => item.id === channelId ? { ...item, restricted: !!channelForm.allowedUserIds.length } : item)); setModal(null); } catch (cause) { setError((cause as Error).message); } };
  const openAccess = async (id: string) => { setChannelId(id); const ids = await api<string[]>(`/channels/${id}/access`); setChannelForm((current) => ({ ...current, allowedUserIds: ids })); setModal("access"); };
  const toggleAllowed = (id: string) => setChannelForm((current) => ({ ...current, allowedUserIds: current.allowedUserIds.includes(id) ? current.allowedUserIds.filter((item) => item !== id) : [...current.allowedUserIds, id] }));
  const sendMessage = async () => { if (!body.trim() && !pendingFile) return; try { let attachmentId: string | undefined; if (pendingFile) attachmentId = (await uploadFile<Attachment>(pendingFile, pendingFile.name)).id; getSocket().emit("message:send", { channelId, body, attachmentId }); setBody(""); setPendingFile(null); setShowTools(false); } catch (cause) { setError((cause as Error).message); } };
  const sendFriendRequest = async (event: React.FormEvent) => { event.preventDefault(); try { await api("/friends/requests", { method: "POST", body: JSON.stringify({ username: friendName }) }); setFriendName(""); setError("Solicitação enviada."); } catch (cause) { setError((cause as Error).message); } };
  const answerRequest = async (id: string, status: "accepted" | "rejected") => { await api(`/friends/requests/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); loadSocial(); };
  const saveTheme = async (next = theme) => { applyTheme(next); await api("/preferences", { method: "PUT", body: JSON.stringify(next) }); };
  const format = (left: string, right = left) => { const input = textInput.current; if (!input) return; const start = input.selectionStart; const end = input.selectionEnd; setBody(body.slice(0, start) + left + body.slice(start, end) + right + body.slice(end)); setTimeout(() => input.focus(), 0); };
  const toggleAudioRecording = async () => { if (recording) { audioRecorder.current?.stop(); setRecording(false); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: { deviceId: audioInputId ? { exact: audioInputId } : undefined } }); const recorder = new MediaRecorder(stream); audioChunks.current = []; recorder.ondataavailable = (event) => event.data.size && audioChunks.current.push(event.data); recorder.onstop = async () => { stream.getTracks().forEach((track) => track.stop()); const blob = new Blob(audioChunks.current, { type: recorder.mimeType }); try { const file = await uploadFile<Attachment>(blob, `audio-${Date.now()}.webm`); getSocket().emit("message:send", { channelId, body: "", attachmentId: file.id }); } catch (cause) { setError((cause as Error).message); } }; recorder.start(); audioRecorder.current = recorder; setRecording(true); } catch (cause) { setError(friendlyPermission(cause)); } };
  const share = () => { const [width, height, frameRate] = quality.split("x").map(Number); rtc.shareScreen({ width, height, frameRate }).catch((cause) => setError(friendlyPermission(cause))); };
  const toggleCallRecording = () => { if (callRecorder.current) { callRecorder.current.stop(); callRecorder.current = null; return; } if (!rtc.localStream) return; const recorder = new MediaRecorder(rtc.localStream); callChunks.current = []; recorder.ondataavailable = (event) => event.data.size && callChunks.current.push(event.data); recorder.onstop = () => { const url = URL.createObjectURL(new Blob(callChunks.current, { type: recorder.mimeType })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `friendcord-${Date.now()}.webm`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }; recorder.start(); callRecorder.current = recorder; };
  const logout = () => { rtc.leave(); localStorage.removeItem("friendcord_token"); resetSocket(); location.reload(); };
  const openProfile = async () => { setProfileForm({ username: user.username, displayName: user.displayName, avatar: null, banner: null }); setDevices(await navigator.mediaDevices.enumerateDevices()); setModal("profile"); };
  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); try { const avatarId = profileForm.avatar ? (await uploadFile<Attachment>(profileForm.avatar, profileForm.avatar.name)).id : undefined; const bannerId = profileForm.banner ? (await uploadFile<Attachment>(profileForm.banner, profileForm.banner.name)).id : undefined; const result = await api<{ user: PublicUser; token: string }>("/me", { method: "PATCH", body: JSON.stringify({ username: profileForm.username, displayName: profileForm.displayName, ...(avatarId ? { avatarId } : {}), ...(bannerId ? { bannerId } : {}) }) }); localStorage.setItem("friendcord_token", result.token); localStorage.setItem("friendcord_audio_input", audioInputId); localStorage.setItem("friendcord_audio_output", audioOutputId); localStorage.setItem("friendcord_camera", cameraId); const socket = getSocket(); socket.disconnect(); getSocket().connect(); setUser(result.user); setModal(null); setError("Perfil e dispositivos atualizados."); } catch (cause) { setError((cause as Error).message); } };
  const openServerSettings = () => { if (!currentRoom) return; setServerForm({ name: currentRoom.name, icon: null, banner: null }); setModal("serverSettings"); };
  const saveServerSettings = async (event: React.FormEvent) => { event.preventDefault(); try { const iconId = serverForm.icon ? (await uploadFile<Attachment>(serverForm.icon, serverForm.icon.name)).id : undefined; const bannerId = serverForm.banner ? (await uploadFile<Attachment>(serverForm.banner, serverForm.banner.name)).id : undefined; const room = await api<Room>(`/rooms/${roomId}`, { method: "PATCH", body: JSON.stringify({ name: serverForm.name, ...(iconId ? { iconId } : {}), ...(bannerId ? { bannerId } : {}) }) }); setRooms((current) => current.map((item) => item.id === roomId ? { ...item, ...room } : item)); setModal(null); } catch (cause) { setError((cause as Error).message); } };

  const HomeNav = () => <aside className="home-nav"><div className="nav-brand">F</div><button className={view === "servers" ? "active" : ""} onClick={() => setView("servers")}>◈<span>Servidores</span></button><button className={view === "friends" ? "active" : ""} onClick={() => setView("friends")}>☻<span>Amigos</span></button><button className={view === "requests" ? "active" : ""} onClick={() => setView("requests")}>✉<span>Solicitações{requests.length ? ` (${requests.length})` : ""}</span></button><button className={view === "themes" ? "active" : ""} onClick={() => setView("themes")}>✦<span>Aparência</span></button>{user.siteRole === "superadmin" && <button className={view === "admin" ? "active" : ""} onClick={() => setView("admin")}>♛<span>Admin global</span></button>}<footer><Avatar person={user}/><button className="profile-summary" onClick={openProfile}><strong>{user.displayName}</strong><small>@{user.username}</small></button><button onClick={logout}>⏻</button></footer></aside>;
  const pageTitle: Record<Exclude<View, "room">, string> = { servers: "Seus servidores", friends: "Amigos", requests: "Solicitações de amizade", themes: "Sua aparência", admin: "Administração global" };

  return <div className={view === "room" ? "room-shell" : "home-shell"}>
    {view !== "room" && <><HomeNav/><main className="home-main"><header><div><small>FRIENDCORD</small><h1>{pageTitle[view]}</h1></div>{error && <button className="notice" onClick={() => setError("")}>{error} ×</button>}</header>
      {view === "servers" && <section className="server-page"><div className="action-row"><button className="primary" onClick={() => setModal("server")}>＋ Criar servidor</button><button onClick={() => setModal("invite")}>↗ Entrar com convite</button></div><div className="server-grid">{rooms.map((room) => <button className="server-card" key={room.id} onClick={() => openRoom(room.id)} style={room.bannerUrl ? { backgroundImage: `linear-gradient(#161922cc,#161922ee),url(${mediaUrl(room.bannerUrl)})` } : undefined}><span>{room.iconUrl ? <img src={mediaUrl(room.iconUrl)} alt=""/> : room.name.slice(0, 2).toUpperCase()}</span><div><strong>{room.name}</strong><small>{room.role === "owner" ? "Proprietário" : room.role === "admin" ? "Administrador" : "Membro"}</small></div>→</button>)}{!rooms.length && <div className="empty-state"><b>Você ainda não está em nenhum servidor.</b><p>Crie seu espaço ou entre usando um convite.</p></div>}</div></section>}
      {view === "friends" && <section><form className="friend-search" onSubmit={sendFriendRequest}><span>@</span><input placeholder="nomedeusuario" value={friendName.replace(/^@/, "")} onChange={(event) => setFriendName(event.target.value)}/><button className="primary">Adicionar amigo</button></form><div className="people-list">{friends.map((friend) => <article key={friend.id}><Avatar person={friend}/><div><strong>{friend.displayName}</strong><small>@{friend.username} · {friend.realName}</small></div><span className={online.some((item) => item.id === friend.id) ? "online-pill" : "offline-pill"}>{online.some((item) => item.id === friend.id) ? "Online" : "Offline"}</span></article>)}{!friends.length && <div className="empty-state">Adicione alguém usando o @nomedeusuario.</div>}</div></section>}
      {view === "requests" && <section className="people-list">{requests.map((request) => <article key={request.id}><Avatar person={request.sender}/><div><strong>{request.sender.displayName}</strong><small>@{request.sender.username} · {request.sender.realName}</small></div><button className="primary" onClick={() => answerRequest(request.id, "accepted")}>Aceitar</button><button onClick={() => answerRequest(request.id, "rejected")}>Recusar</button></article>)}{!requests.length && <div className="empty-state">Nenhuma solicitação pendente.</div>}</section>}
      {view === "themes" && <section className="theme-panel"><div className="theme-preview"><div className="preview-sidebar"/><div><h3>Seu FriendCord, suas cores</h3><p>As preferências ficam salvas na sua conta.</p><button className="primary">Exemplo</button></div></div><label>Estilo<select value={theme.mode} onChange={(event) => applyTheme({ ...theme, mode: event.target.value as Theme["mode"] })}><option value="gradient">Degradê colorido</option><option value="solid">Cor única</option></select></label><label>Cor principal<input type="color" value={theme.primary} onChange={(event) => applyTheme({ ...theme, primary: event.target.value })}/></label><label>Cor secundária<input type="color" value={theme.secondary} onChange={(event) => applyTheme({ ...theme, secondary: event.target.value })}/></label><label>Fundo<input type="color" value={theme.surface} onChange={(event) => applyTheme({ ...theme, surface: event.target.value })}/></label><button className="primary" onClick={() => saveTheme()}>Salvar aparência</button></section>}
      {view === "admin" && <section><div className="admin-banner">♛ Você pode visualizar e administrar todos os servidores.</div><div className="server-grid">{adminRooms.map((room) => <article className="server-card" key={room.id}><span>{room.name.slice(0, 2).toUpperCase()}</span><div><strong>{room.name}</strong><small>Dono: @{room.owner} · {room.memberCount} membros</small></div><button className="primary" onClick={async () => { await api(`/admin/rooms/${room.id}/join`, { method: "POST" }); await loadRooms(); openRoom(room.id); }}>Entrar como admin</button></article>)}</div></section>}
    </main></>}

    {view === "room" && <><aside className="server-rail"><button className="home-button" onClick={() => { rtc.leave(); setView("servers"); }}>⌂</button>{rooms.map((room) => <button key={room.id} className={room.id === roomId ? "active" : ""} onClick={() => openRoom(room.id)}>{room.iconUrl ? <img src={mediaUrl(room.iconUrl)} alt=""/> : room.name.slice(0, 2).toUpperCase()}</button>)}</aside><aside className="channels"><header style={currentRoom?.bannerUrl ? { backgroundImage: `linear-gradient(#1b1e26cc,#1b1e26),url(${mediaUrl(currentRoom.bannerUrl)})` } : undefined}><div><small>SERVIDOR</small><strong>{currentRoom?.name}</strong></div><div className="server-actions">{canManage && <button onClick={openServerSettings}>⚙</button>}{canManage && <button onClick={createInvite}>Convidar</button>}</div></header><nav><div className="channel-title">CANAIS DE TEXTO {canManage && <button onClick={() => { setChannelForm({ name: "", kind: "text", restricted: false, allowedUserIds: [] }); setModal("channel"); }}>＋</button>}</div>{channels.filter((item) => item.kind === "text").map((item) => <div className={item.id === channelId ? "channel-row selected" : "channel-row"} key={item.id}><button onClick={() => setChannelId(item.id)}># {item.name}</button>{item.restricted && <span>🔒</span>}{canManage && <button onClick={() => openAccess(item.id)}>⚙</button>}</div>)}<div className="channel-title">CANAIS DE VOZ {canManage && <button onClick={() => { setChannelForm({ name: "", kind: "voice", restricted: false, allowedUserIds: [] }); setModal("channel"); }}>＋</button>}</div>{channels.filter((item) => item.kind === "voice").map((item) => <div className="channel-row" key={item.id}><button onClick={() => { setChannelId(item.id); rtc.join(item.id, audioInputId, cameraId).catch((cause) => setError(friendlyPermission(cause))); }}>🔊 {item.name}</button>{item.restricted && <span>🔒</span>}{canManage && <button onClick={() => openAccess(item.id)}>⚙</button>}</div>)}</nav><footer><Avatar person={user}/><button className="profile-summary" onClick={openProfile}><strong>{user.displayName}</strong><small>@{user.username}</small></button><button onClick={() => { rtc.leave(); setView("servers"); }}>⌂</button></footer></aside><main className="chat-main"><header><div><small>{currentChannel?.kind === "voice" ? "CANAL DE VOZ" : "CANAL DE TEXTO"}</small><h2>{currentChannel?.kind === "voice" ? "🔊" : "#"} {currentChannel?.name}</h2></div>{error && <button className="notice" onClick={() => setError("")}>{error} ×</button>}</header>
      {rtc.inCall && <section className="call"><div className="videos">{rtc.localStream && <VideoTile stream={rtc.localStream} muted label="Você" avatarUrl={user.avatarUrl} videoVisible={rtc.videoEnabled || rtc.screenSharing} screenSharing={rtc.screenSharing}/>} {rtc.remotePeers.map((peer) => <VideoTile key={peer.id} stream={peer.stream} volume={volume} outputDeviceId={audioOutputId} label={peer.user.displayName} avatarUrl={peer.user.avatarUrl} videoVisible={peer.videoEnabled || peer.screenSharing} screenSharing={peer.screenSharing}/>)}</div><div className="call-controls"><button className={!rtc.audioEnabled ? "control-off" : ""} onClick={rtc.toggleAudio}>{rtc.audioEnabled ? "🎙 Microfone" : "🔇 Ativar microfone"}</button><button className={!rtc.videoEnabled ? "control-off" : ""} onClick={() => rtc.toggleVideo().catch((cause) => setError(friendlyPermission(cause)))}>{rtc.videoEnabled ? "📷 Câmera" : "📷 Ativar câmera"}</button><select value={quality} onChange={(event) => setQuality(event.target.value)}><option value="1280x720x30">720p / 30 FPS</option><option value="1920x1080x30">1080p / 30 FPS</option><option value="1920x1080x60">1080p / 60 FPS</option><option value="2560x1440x30">1440p / 30 FPS</option></select>{rtc.screenSharing ? <button className="danger" onClick={rtc.stopScreen}>⏹ Parar compartilhamento</button> : <button onClick={share}>🖥 Compartilhar tela</button>}<button onClick={toggleCallRecording}>⏺ Gravar local</button><button onClick={() => setShowMedia(!showMedia)}>♫ Mídia</button><label>Volume <input type="range" min="0" max="1" step=".05" value={volume} onChange={(event) => setVolume(Number(event.target.value))}/></label><button className="danger" onClick={rtc.leave}>Sair</button></div>{showMedia && <MediaRoom channelId={channelId}/>}</section>}
      {currentChannel?.kind === "text" && <><section className="message-history">{messages.map((message) => <article key={message.id}><Avatar person={message.author}/><div className="message-content"><div><strong>{message.author.displayName}</strong><time>{new Date(message.createdAt).toLocaleString("pt-BR")}</time></div>{message.body && <MessageText body={message.body}/>} {message.attachment && <AttachmentView file={message.attachment}/>}</div></article>)}</section><section className="composer-wrap">{pendingFile && <div className="pending-file">📎 {pendingFile.name}<button onClick={() => setPendingFile(null)}>×</button></div>}{showTools && <div className="composer-tools"><button onClick={() => fileInput.current?.click()}>📎 Anexar arquivo</button><button onClick={() => format("**")}>B Negrito</button><button onClick={() => format("*")}>I Itálico</button><button onClick={() => format("```\n", "\n```")}>{"</>"} Código</button></div>}<div className="composer"><button className="plus-button" onClick={() => setShowTools(!showTools)}>＋</button><textarea ref={textInput} rows={1} value={body} onChange={(event) => setBody(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); sendMessage(); } }} placeholder={`Mensagem em #${currentChannel.name}`}/><input ref={fileInput} hidden type="file" onChange={(event) => setPendingFile(event.target.files?.[0] ?? null)}/><button className={recording ? "mic-button recording" : "mic-button"} onClick={toggleAudioRecording}>{recording ? "■" : "🎙"}</button><button className="send-button" onClick={sendMessage}>Enviar</button></div></section></>}
    </main><aside className="members"><h3>ONLINE — {members.filter((member) => online.some((item) => item.id === member.id)).length}</h3>{members.filter((member) => online.some((item) => item.id === member.id)).map((member) => <button className="member" key={member.id} onClick={() => member.id === user.id && openProfile()}><span className="status online"/><Avatar person={member}/><div><strong>{member.displayName}</strong><small>@{member.username}</small></div></button>)}<h3>OFFLINE — {members.filter((member) => !online.some((item) => item.id === member.id)).length}</h3>{members.filter((member) => !online.some((item) => item.id === member.id)).map((member) => <button className="member offline-member" key={member.id} onClick={() => member.id === user.id && openProfile()}><span className="status"/><Avatar person={member}/><div><strong>{member.displayName}</strong><small>@{member.username}</small></div></button>)}</aside></>}

    {modal === "server" && <Modal title="Criar um servidor" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createServer}><label>Nome do servidor<input autoFocus value={serverName} onChange={(event) => setServerName(event.target.value)} placeholder="Ex.: Casa dos Amigos" required/></label><button className="primary">Criar servidor</button></form></Modal>}
    {modal === "invite" && <Modal title="Entrar em um servidor" onClose={() => setModal(null)}><form className="modal-form" onSubmit={joinServer}><label>Código ou link do convite<input autoFocus value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} required/></label><button className="primary">Entrar</button></form></Modal>}
    {modal === "inviteLink" && <Modal title="Convide seus amigos" onClose={() => setModal(null)}><div className="modal-form"><p>Este convite vale por 7 dias. Copie o link abaixo:</p><div className="copy-row"><input readOnly value={inviteLink} onFocus={(event) => event.currentTarget.select()}/><button className="primary" onClick={async () => { try { await navigator.clipboard.writeText(inviteLink); setError("Convite copiado."); } catch { setError("O navegador bloqueou a cópia automática. Selecione o link e use Ctrl+C."); } }}>Copiar</button></div></div></Modal>}
    {modal === "profile" && <Modal title="Meu perfil e dispositivos" onClose={() => setModal(null)}><form className="modal-form profile-form" onSubmit={saveProfile}>{user.bannerUrl && <img className="profile-banner" src={mediaUrl(user.bannerUrl)} alt=""/>}<div className="profile-head"><Avatar person={user} size="large"/><div><strong>{user.displayName}</strong><small>@{user.username}</small></div></div><label>Nome exibido<input value={profileForm.displayName} onChange={(event) => setProfileForm({ ...profileForm, displayName: event.target.value })} required/></label><label>Nome de usuário<input value={profileForm.username} pattern="[a-zA-Z0-9_]{3,32}" onChange={(event) => setProfileForm({ ...profileForm, username: event.target.value })} required/><small>De 3 a 32 caracteres: letras, números e _ . O nome precisa estar disponível.</small></label><div className="form-grid"><label>Foto de perfil<input type="file" accept="image/*" onChange={(event) => setProfileForm({ ...profileForm, avatar: event.target.files?.[0] ?? null })}/></label><label>Capa do perfil<input type="file" accept="image/*" onChange={(event) => setProfileForm({ ...profileForm, banner: event.target.files?.[0] ?? null })}/></label></div><hr/><h3>Voz e vídeo</h3><label>Microfone<select value={audioInputId} onChange={(event) => setAudioInputId(event.target.value)}><option value="">Padrão do sistema</option>{devices.filter((item) => item.kind === "audioinput").map((item, index) => <option key={item.deviceId} value={item.deviceId}>{item.label || `Microfone ${index + 1}`}</option>)}</select></label><label>Saída de áudio<select value={audioOutputId} onChange={(event) => setAudioOutputId(event.target.value)}><option value="">Padrão do sistema</option>{devices.filter((item) => item.kind === "audiooutput").map((item, index) => <option key={item.deviceId} value={item.deviceId}>{item.label || `Saída ${index + 1}`}</option>)}</select><small>A troca de saída depende do suporte do navegador.</small></label><label>Câmera<select value={cameraId} onChange={(event) => setCameraId(event.target.value)}><option value="">Padrão do sistema</option>{devices.filter((item) => item.kind === "videoinput").map((item, index) => <option key={item.deviceId} value={item.deviceId}>{item.label || `Câmera ${index + 1}`}</option>)}</select></label><button className="primary">Salvar configurações</button></form></Modal>}
    {modal === "serverSettings" && currentRoom && <Modal title="Configurações do servidor" onClose={() => setModal(null)}><form className="modal-form" onSubmit={saveServerSettings}>{currentRoom.bannerUrl && <img className="profile-banner" src={mediaUrl(currentRoom.bannerUrl)} alt=""/>}<label>Nome do servidor<input value={serverForm.name} onChange={(event) => setServerForm({ ...serverForm, name: event.target.value })} required/></label><div className="form-grid"><label>Ícone do servidor<input type="file" accept="image/*" onChange={(event) => setServerForm({ ...serverForm, icon: event.target.files?.[0] ?? null })}/></label><label>Imagem de capa<input type="file" accept="image/*" onChange={(event) => setServerForm({ ...serverForm, banner: event.target.files?.[0] ?? null })}/></label></div><button className="primary">Salvar servidor</button></form></Modal>}
    {modal === "channel" && <Modal title={`Criar canal de ${channelForm.kind === "voice" ? "voz" : "texto"}`} onClose={() => setModal(null)}><form className="modal-form" onSubmit={createChannel}><label>Nome<input autoFocus value={channelForm.name} onChange={(event) => setChannelForm({ ...channelForm, name: event.target.value })} required/></label><label>Tipo<select value={channelForm.kind} onChange={(event) => setChannelForm({ ...channelForm, kind: event.target.value as "text" | "voice" })}><option value="text">Texto</option><option value="voice">Voz</option></select></label><label className="check"><input type="checkbox" checked={channelForm.restricted} onChange={(event) => setChannelForm({ ...channelForm, restricted: event.target.checked })}/> Restringir a membros selecionados</label>{channelForm.restricted && <MemberChecks members={members} selected={channelForm.allowedUserIds} toggle={toggleAllowed}/>}<button className="primary">Criar canal</button></form></Modal>}
    {modal === "access" && <Modal title="Quem pode acessar este canal?" onClose={() => setModal(null)}><div className="modal-form"><p>Sem pessoas selecionadas, todos os membros podem acessar. Donos e administradores sempre mantêm acesso.</p><MemberChecks members={members} selected={channelForm.allowedUserIds} toggle={toggleAllowed}/><button className="primary" onClick={saveAccess}>Salvar permissões</button></div></Modal>}
  </div>;
}

function MemberChecks({ members, selected, toggle }: { members: PublicUser[]; selected: string[]; toggle: (id: string) => void }) {
  return <div className="member-checks">{members.map((member) => <label key={member.id}><input type="checkbox" checked={selected.includes(member.id)} onChange={() => toggle(member.id)}/><Avatar person={member}/><span>{member.displayName}<small>@{member.username}</small></span></label>)}</div>;
}
