import { useEffect, useRef, useState } from "react";
import type { Attachment, Channel, ChatMessage, DirectMessage, PublicUser, Room } from "@friendcord/shared";
import { API_URL, api, getToken, uploadFile } from "./api";
import { getSocket, resetSocket } from "./socket";
import { useWebRTC } from "./hooks/useWebRTC";
import { VideoTile } from "./components/VideoTile";
import { MediaRoom } from "./components/MediaRoom";

type RoomWithRole = Room & { role: "owner" | "admin" | "member" };
type View = "servers" | "friends" | "requests" | "themes" | "admin" | "dm" | "room";
type Theme = { mode: "solid" | "gradient"; primary: string; secondary: string; surface: string };
type FriendRequest = { id: string; sender: PublicUser; createdAt: string };
type AdminRoom = Room & { owner: string; memberCount: number };
type RolePermissions = { manageChannels: boolean; manageMembers: boolean; createInvites: boolean; sendMessages: boolean; connectVoice: boolean };
type ModalName = "server" | "invite" | "inviteLink" | "channel" | "access" | "profile" | "serverSettings" | "userCard" | "code" | "roles" | null;

const mediaUrl = (path?: string | null) => path ? `${API_URL}${path}` : "";
const isOnline = (list: PublicUser[], id: string) => list.some((item) => item.id === id);
function friendlyPermission(error: unknown) { const cause = error as DOMException; return cause?.name === "NotAllowedError" ? "Permissão recusada. Libere o dispositivo no cadeado do navegador." : cause?.message || "Não foi possível acessar o dispositivo."; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="modal"><header><h2>{title}</h2><button onClick={onClose}>×</button></header>{children}</section></div>; }
function Avatar({ person, size = "normal" }: { person: Pick<PublicUser, "displayName" | "avatarUrl">; size?: "normal" | "large" }) { return <div className={`avatar ${size === "large" ? "avatar-large" : ""}`}>{person.avatarUrl ? <img src={mediaUrl(person.avatarUrl)} alt=""/> : person.displayName.slice(0, 1).toUpperCase()}</div>; }
function MessageText({ body }: { body: string }) { return <div className="message-body">{body.split("```").map((part, index) => index % 2 ? <pre key={index}><code>{part.replace(/^\w+\n/, "")}</code></pre> : <span key={index}>{part.split(/(https?:\/\/\S+\.(?:gif|webp))/i).map((piece, pieceIndex) => /^https?:\/\/.+\.(gif|webp)$/i.test(piece) ? <img className="inline-gif" src={piece} alt="GIF" key={pieceIndex}/> : piece)}</span>)}</div>; }
function AttachmentView({ file }: { file: Attachment }) { const source = `${API_URL}${file.url}`; if (file.mimeType.startsWith("audio/")) return <audio className="audio-message" controls src={source}/>; if (file.mimeType.startsWith("image/")) return <a href={source} target="_blank"><img className="image-attachment" src={source} alt={file.filename}/></a>; return <a className="file-attachment" href={source} target="_blank" download>📎 <span>{file.filename}</span><small>{Math.ceil(file.sizeBytes / 1024)} KB</small></a>; }

function Composer(props: { body: string; setBody: (value: string) => void; inputRef: React.RefObject<HTMLTextAreaElement | null>; fileInput: React.RefObject<HTMLInputElement | null>; pendingFile: File | null; setPendingFile: (file: File | null) => void; showTools: boolean; setShowTools: (value: boolean) => void; showEmoji: boolean; setShowEmoji: (value: boolean) => void; recording: boolean; onRecord: () => void; onSend: () => void; onCode: () => void; placeholder: string }) {
  const { body, setBody, inputRef, fileInput, pendingFile, setPendingFile, showTools, setShowTools, showEmoji, setShowEmoji, recording, onRecord, onSend, onCode, placeholder } = props;
  return <section className="composer-wrap">{pendingFile && <div className="pending-file">📎 {pendingFile.name}<button onClick={() => setPendingFile(null)}>×</button></div>}{showTools && <div className="composer-tools"><button onClick={() => fileInput.current?.click()}>📎 Arquivo</button><button onClick={() => setBody(`${body}**texto**`)}>B Negrito</button><button onClick={() => setBody(`${body}*texto*`)}>I Itálico</button><button onClick={onCode}>{"</>"} Caixa de código</button></div>}{showEmoji && <div className="emoji-picker">{["😀","😂","😍","😎","😭","🔥","❤️","👍","🎉","🤖","🎮","🎵"].map((emoji) => <button key={emoji} onClick={() => setBody(body + emoji)}>{emoji}</button>)}<input placeholder="URL de GIF + Enter" onKeyDown={(event) => { if (event.key === "Enter") { setBody(`${body}${body ? " " : ""}${event.currentTarget.value}`); event.currentTarget.value = ""; } }}/></div>}<div className="composer"><button className="plus-button" onClick={() => setShowTools(!showTools)}>＋</button><textarea ref={inputRef} rows={1} value={body} onChange={(event) => setBody(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); onSend(); } }} placeholder={placeholder}/><input ref={fileInput} hidden type="file" onChange={(event) => setPendingFile(event.target.files?.[0] ?? null)}/><button className="emoji-button" onClick={() => setShowEmoji(!showEmoji)}>☺ GIF</button><button className={recording ? "mic-button recording" : "mic-button"} onClick={onRecord}>{recording ? "■" : "🎙️"}</button><button className="send-button" onClick={onSend}>Enviar</button></div></section>;
}

function Auth({ onDone }: { onDone: (user: PublicUser) => void }) {
  const [register, setRegister] = useState(false); const [form, setForm] = useState({ displayName: "", realName: "", email: "", username: "", password: "" }); const [error, setError] = useState("");
  const field = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: event.target.value });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const data = await api<{ token: string; user: PublicUser }>(`/auth/${register ? "register" : "login"}`, { method: "POST", body: JSON.stringify(form) }); localStorage.setItem("friendcord_token", data.token); onDone(data.user); } catch (cause) { setError((cause as Error).message); } };
  return <main className="auth"><form onSubmit={submit}><div className="auth-logo">F</div><h1>FriendCord</h1>{register && <><label>Nome real<input value={form.realName} onChange={field("realName")} required/></label><label>Nome exibido<input value={form.displayName} onChange={field("displayName")} required/></label><label>E-mail<input type="email" value={form.email} onChange={field("email")} required/></label></>}<label>Usuário<input value={form.username} onChange={field("username")} minLength={3} required/></label><label>Senha<input type="password" value={form.password} onChange={field("password")} minLength={8} required/></label>{error && <div className="error">{error}</div>}<button className="primary">{register ? "Criar conta" : "Entrar"}</button><button className="link" type="button" onClick={() => setRegister(!register)}>{register ? "Já tenho conta" : "Criar cadastro"}</button></form></main>;
}

export default function App() {
  const [user, setUser] = useState<PublicUser | null>(null); const [view, setView] = useState<View>("servers"); const [rooms, setRooms] = useState<RoomWithRole[]>([]); const [roomId, setRoomId] = useState(""); const [channels, setChannels] = useState<Channel[]>([]); const [channelId, setChannelId] = useState(""); const [members, setMembers] = useState<PublicUser[]>([]); const [messages, setMessages] = useState<ChatMessage[]>([]); const [dmMessages, setDmMessages] = useState<DirectMessage[]>([]); const [selectedUser, setSelectedUser] = useState<PublicUser | null>(null); const [online, setOnline] = useState<PublicUser[]>([]); const [friends, setFriends] = useState<PublicUser[]>([]); const [requests, setRequests] = useState<FriendRequest[]>([]); const [adminRooms, setAdminRooms] = useState<AdminRoom[]>([]); const [adminUsers, setAdminUsers] = useState<PublicUser[]>([]);
  const [body, setBody] = useState(""); const [error, setError] = useState(""); const [modal, setModal] = useState<ModalName>(null); const [serverName, setServerName] = useState(""); const [inviteCode, setInviteCode] = useState(""); const [inviteLink, setInviteLink] = useState(""); const [friendName, setFriendName] = useState(""); const [codeDraft, setCodeDraft] = useState(""); const [channelForm, setChannelForm] = useState({ name: "", kind: "text" as "text" | "voice", restricted: false, allowedUserIds: [] as string[] }); const [pendingFile, setPendingFile] = useState<File | null>(null); const [recording, setRecording] = useState(false); const [showTools, setShowTools] = useState(false); const [showEmoji, setShowEmoji] = useState(false); const [showMedia, setShowMedia] = useState(false); const [quality, setQuality] = useState("1920x1080x30"); const [volume, setVolume] = useState(1); const [compact, setCompact] = useState(localStorage.getItem("friendcord_compact") === "true");
  const [devices, setDevices] = useState<MediaDeviceInfo[]>([]); const [audioInputId, setAudioInputId] = useState(localStorage.getItem("friendcord_audio_input") ?? ""); const [audioOutputId, setAudioOutputId] = useState(localStorage.getItem("friendcord_audio_output") ?? ""); const [cameraId, setCameraId] = useState(localStorage.getItem("friendcord_camera") ?? "");
  const [profileForm, setProfileForm] = useState({ username: "", displayName: "", customStatus: "", avatar: null as File | null, banner: null as File | null }); const [serverForm, setServerForm] = useState({ name: "", icon: null as File | null, banner: null as File | null }); const [theme, setTheme] = useState<Theme>({ mode: "gradient", primary: "#7c5cff", secondary: "#22c5b5", surface: "#20232d" });
  const defaults: Record<"admin" | "member", RolePermissions> = { admin: { manageChannels: true, manageMembers: true, createInvites: true, sendMessages: true, connectVoice: true }, member: { manageChannels: false, manageMembers: false, createInvites: false, sendMessages: true, connectVoice: true } }; const [rolePermissions, setRolePermissions] = useState(defaults);
  const fileInput = useRef<HTMLInputElement>(null); const textInput = useRef<HTMLTextAreaElement>(null); const historyRef = useRef<HTMLElement>(null); const audioRecorder = useRef<MediaRecorder | null>(null); const audioChunks = useRef<Blob[]>([]); const callRecorder = useRef<MediaRecorder | null>(null); const callChunks = useRef<Blob[]>([]); const rtc = useWebRTC();
  const currentRoom = rooms.find((room) => room.id === roomId); const currentChannel = channels.find((channel) => channel.id === channelId); const canManage = user?.siteRole === "superadmin" || currentRoom?.role === "owner" || currentRoom?.role === "admin";
  const applyTheme = (next: Theme) => { setTheme(next); const root = document.documentElement; root.style.setProperty("--primary", next.primary); root.style.setProperty("--secondary", next.secondary); root.style.setProperty("--surface", next.surface); root.style.setProperty("--accent-bg", next.mode === "gradient" ? `linear-gradient(135deg, ${next.primary}, ${next.secondary})` : next.primary); };
  const loadRooms = () => api<RoomWithRole[]>("/rooms").then(setRooms); const loadSocial = () => { api<PublicUser[]>("/friends").then(setFriends); api<FriendRequest[]>("/friends/requests").then(setRequests); };
  useEffect(() => { if (getToken()) api<PublicUser>("/me").then(setUser).catch(() => localStorage.removeItem("friendcord_token")); }, []);
  useEffect(() => { if (!user) return; loadRooms(); loadSocial(); api<Theme>("/preferences").then(applyTheme); const socket = getSocket(); const presence = (items: PublicUser[]) => setOnline(items); const notification = (item: { title: string; body: string }) => setError(`${item.title}: ${item.body}`); socket.on("presence:update", presence); socket.on("notification", notification); socket.connect(); return () => { socket.off("presence:update", presence); socket.off("notification", notification); }; }, [user?.id]);
  useEffect(() => { if (view === "admin" && user?.siteRole === "superadmin") Promise.all([api<AdminRoom[]>("/admin/rooms"), api<PublicUser[]>("/admin/users")]).then(([nextRooms, nextUsers]) => { setAdminRooms(nextRooms); setAdminUsers(nextUsers); }).catch((cause) => setError(`Admin: ${(cause as Error).message}`)); }, [view, user?.siteRole]);
  useEffect(() => { if (!roomId || view !== "room") return; Promise.all([api<Channel[]>(`/rooms/${roomId}/channels`), api<PublicUser[]>(`/rooms/${roomId}/members`)]).then(([nextChannels, nextMembers]) => { setChannels(nextChannels); setMembers(nextMembers); setChannelId(nextChannels.find((item) => item.kind === "text")?.id ?? ""); }); }, [roomId, view]);
  useEffect(() => { if (!channelId || currentChannel?.kind !== "text") return; api<ChatMessage[]>(`/channels/${channelId}/messages`).then(setMessages); const socket = getSocket(); socket.emit("channel:join", channelId); const receive = (item: ChatMessage) => item.channelId === channelId && setMessages((current) => [...current, item]); socket.on("message:new", receive); return () => { socket.off("message:new", receive); }; }, [channelId, currentChannel?.kind]);
  useEffect(() => { if (view !== "dm" || !selectedUser) return; api<DirectMessage[]>(`/dms/${selectedUser.id}/messages`).then(setDmMessages).catch((cause) => setError((cause as Error).message)); const socket = getSocket(); const receive = (item: DirectMessage) => { if (item.senderId === selectedUser.id || item.receiverId === selectedUser.id || item.author.username.startsWith("friend")) setDmMessages((current) => [...current, item]); }; socket.on("dm:new", receive); return () => { socket.off("dm:new", receive); }; }, [view, selectedUser?.id]);
  useEffect(() => { historyRef.current?.scrollTo({ top: historyRef.current.scrollHeight, behavior: "smooth" }); }, [messages, dmMessages]);
  if (!user) return <Auth onDone={setUser}/>;

  const openRoom = (id: string) => { rtc.leave(); setRoomId(id); setView("room"); }; const openDirect = (person: PublicUser) => { setSelectedUser(person); setBody(""); setModal(null); setView("dm"); };
  const openProfile = async () => { setProfileForm({ username: user.username, displayName: user.displayName, customStatus: user.customStatus ?? "", avatar: null, banner: null }); setDevices(await navigator.mediaDevices.enumerateDevices()); setModal("profile"); }; const openUserCard = (person: PublicUser) => person.id === user.id ? openProfile() : (setSelectedUser(person), setModal("userCard"));
  const askAssistant = (text: string, target: { channelId?: string; receiverId?: string }) => { const match = text.match(/@(gpt|gemini)\b[,:]?\s*(.+)/is); if (match) getSocket().emit("ai:ask", { ...target, provider: match[1].toLowerCase() as "gpt" | "gemini", prompt: match[2] }); };
  const send = async (direct: boolean) => { if ((!body.trim() && !pendingFile) || (direct && !selectedUser)) return; try { const attachmentId = pendingFile ? (await uploadFile<Attachment>(pendingFile, pendingFile.name)).id : undefined; if (direct && selectedUser) { getSocket().emit("dm:send", { receiverId: selectedUser.id, body, attachmentId }); askAssistant(body, { receiverId: selectedUser.id }); } else { getSocket().emit("message:send", { channelId, body, attachmentId }); askAssistant(body, { channelId }); } setBody(""); setPendingFile(null); setShowTools(false); setShowEmoji(false); } catch (cause) { setError((cause as Error).message); } };
  const toggleAudioRecording = async () => { if (recording) { audioRecorder.current?.stop(); setRecording(false); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: { deviceId: audioInputId ? { exact: audioInputId } : undefined } }); const recorder = new MediaRecorder(stream); audioChunks.current = []; recorder.ondataavailable = (event) => event.data.size && audioChunks.current.push(event.data); recorder.onstop = async () => { stream.getTracks().forEach((track) => track.stop()); const file = await uploadFile<Attachment>(new Blob(audioChunks.current, { type: recorder.mimeType }), `audio-${Date.now()}.webm`); if (view === "dm" && selectedUser) getSocket().emit("dm:send", { receiverId: selectedUser.id, body: "", attachmentId: file.id }); else getSocket().emit("message:send", { channelId, body: "", attachmentId: file.id }); }; recorder.start(); audioRecorder.current = recorder; setRecording(true); } catch (cause) { setError(friendlyPermission(cause)); } };
  const createServer = async (event: React.FormEvent) => { event.preventDefault(); const room = await api<RoomWithRole>("/rooms", { method: "POST", body: JSON.stringify({ name: serverName }) }); setRooms([...rooms, room]); setModal(null); openRoom(room.id); }; const joinServer = async (event: React.FormEvent) => { event.preventDefault(); const result = await api<{ roomId: string }>(`/invites/${inviteCode.split("invite=").pop()!}/join`, { method: "POST" }); await loadRooms(); setModal(null); openRoom(result.roomId); };
  const createInvite = async () => { const result = await api<{ code: string }>(`/rooms/${roomId}/invites`, { method: "POST" }); setInviteLink(`${location.origin}?invite=${result.code}`); setModal("inviteLink"); }; const createChannel = async (event: React.FormEvent) => { event.preventDefault(); const channel = await api<Channel>(`/rooms/${roomId}/channels`, { method: "POST", body: JSON.stringify({ ...channelForm, allowedUserIds: channelForm.restricted ? channelForm.allowedUserIds : [] }) }); setChannels([...channels, channel]); setModal(null); };
  const openAccess = async (id: string) => { setChannelId(id); const ids = await api<string[]>(`/channels/${id}/access`); setChannelForm((current) => ({ ...current, allowedUserIds: ids })); setModal("access"); }; const toggleAllowed = (id: string) => setChannelForm((current) => ({ ...current, allowedUserIds: current.allowedUserIds.includes(id) ? current.allowedUserIds.filter((item) => item !== id) : [...current.allowedUserIds, id] })); const saveAccess = async () => { await api(`/channels/${channelId}/access`, { method: "PUT", body: JSON.stringify({ userIds: channelForm.allowedUserIds }) }); setModal(null); };
  const sendFriendRequest = async (event?: React.FormEvent, username = friendName) => { event?.preventDefault(); await api("/friends/requests", { method: "POST", body: JSON.stringify({ username }) }); setFriendName(""); setError("Solicitação enviada."); }; const answerRequest = async (id: string, status: "accepted" | "rejected") => { await api(`/friends/requests/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); loadSocial(); };
  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); const avatarId = profileForm.avatar ? (await uploadFile<Attachment>(profileForm.avatar, profileForm.avatar.name)).id : undefined; const bannerId = profileForm.banner ? (await uploadFile<Attachment>(profileForm.banner, profileForm.banner.name)).id : undefined; const result = await api<{ user: PublicUser; token: string }>("/me", { method: "PATCH", body: JSON.stringify({ username: profileForm.username, displayName: profileForm.displayName, customStatus: profileForm.customStatus, ...(avatarId ? { avatarId } : {}), ...(bannerId ? { bannerId } : {}) }) }); localStorage.setItem("friendcord_token", result.token); localStorage.setItem("friendcord_audio_input", audioInputId); localStorage.setItem("friendcord_audio_output", audioOutputId); localStorage.setItem("friendcord_camera", cameraId); getSocket().disconnect(); getSocket().connect(); setUser(result.user); setModal(null); };
  const saveServer = async (event: React.FormEvent) => { event.preventDefault(); const iconId = serverForm.icon ? (await uploadFile<Attachment>(serverForm.icon, serverForm.icon.name)).id : undefined; const bannerId = serverForm.banner ? (await uploadFile<Attachment>(serverForm.banner, serverForm.banner.name)).id : undefined; const room = await api<Room>(`/rooms/${roomId}`, { method: "PATCH", body: JSON.stringify({ name: serverForm.name, ...(iconId ? { iconId } : {}), ...(bannerId ? { bannerId } : {}) }) }); setRooms((current) => current.map((item) => item.id === roomId ? { ...item, ...room } : item)); setModal(null); };
  const openRoles = async () => { const rows = await api<Array<{ role: "admin" | "member"; permissions: RolePermissions }>>(`/rooms/${roomId}/permissions`); setRolePermissions((current) => ({ ...current, ...Object.fromEntries(rows.map((row) => [row.role, row.permissions])) })); setModal("roles"); }; const saveRole = (role: "admin" | "member") => api(`/rooms/${roomId}/permissions`, { method: "PUT", body: JSON.stringify({ role, permissions: rolePermissions[role] }) }); const changeMemberRole = async (person: PublicUser, role: "admin" | "member") => { await api(`/rooms/${roomId}/members/${person.id}`, { method: "PATCH", body: JSON.stringify({ role }) }); setMembers((current) => current.map((item) => item.id === person.id ? { ...item, role } : item)); }; const changeSiteRole = async (person: PublicUser, siteRole: "user" | "superadmin") => { await api(`/admin/users/${person.id}/role`, { method: "PATCH", body: JSON.stringify({ siteRole }) }); setAdminUsers((current) => current.map((item) => item.id === person.id ? { ...item, siteRole } : item)); };
  const share = () => { const [width, height, frameRate] = quality.split("x").map(Number); rtc.shareScreen({ width, height, frameRate }).catch((cause) => setError(friendlyPermission(cause))); }; const toggleCallRecording = () => { if (callRecorder.current) { callRecorder.current.stop(); callRecorder.current = null; return; } if (!rtc.localStream) return; const recorder = new MediaRecorder(rtc.localStream); callChunks.current = []; recorder.ondataavailable = (event) => event.data.size && callChunks.current.push(event.data); recorder.onstop = () => { const url = URL.createObjectURL(new Blob(callChunks.current, { type: recorder.mimeType })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `friendcord-${Date.now()}.webm`; anchor.click(); }; recorder.start(); callRecorder.current = recorder; };
  const logout = () => { rtc.leave(); localStorage.removeItem("friendcord_token"); resetSocket(); location.reload(); }; const composerProps = { body, setBody, inputRef: textInput, fileInput, pendingFile, setPendingFile, showTools, setShowTools, showEmoji, setShowEmoji, recording, onRecord: toggleAudioRecording, onCode: () => setModal("code") };
  const HomeNav = () => <aside className="home-nav"><div className="nav-brand">F</div>{([['servers','◈','Servidores'],['friends','☻','Amigos'],['requests','✉','Solicitações'],['themes','✦','Aparência']] as const).map(([target, icon, label]) => <button key={target} className={view === target ? "active" : ""} onClick={() => setView(target)}>{icon}<span>{label}</span></button>)}{user.siteRole === "superadmin" && <button className={view === "admin" ? "active" : ""} onClick={() => setView("admin")}>♛<span>Admin global</span></button>}<footer><Avatar person={user}/><button className="profile-summary" onClick={openProfile}><strong>{user.displayName}</strong><small>@{user.username}</small></button><button onClick={logout}>⏻</button></footer></aside>;
  const pageTitle = view === "dm" && selectedUser ? `Conversa com ${selectedUser.displayName}` : ({ servers: "Seus servidores", friends: "Amigos", requests: "Solicitações de amizade", themes: "Sua aparência", admin: "Administração global", dm: "Mensagem privada" } as Record<Exclude<View,"room">,string>)[view as Exclude<View,"room">];

  return <div className={view === "room" ? "room-shell" : "home-shell"}>{view !== "room" && <><HomeNav/><main className={`home-main ${view === "dm" ? "dm-main" : ""}`}><header><div><small>FRIENDCORD</small><h1>{pageTitle}</h1></div>{error && <button className="notice" onClick={() => setError("")}>{error} ×</button>}</header>
    {view === "servers" && <section><div className="action-row"><button className="primary" onClick={() => setModal("server")}>＋ Criar servidor</button><button onClick={() => setModal("invite")}>↗ Entrar com convite</button></div><div className="server-grid">{rooms.map((room) => <button className="server-card" key={room.id} onClick={() => openRoom(room.id)}><span>{room.iconUrl ? <img src={mediaUrl(room.iconUrl)} alt=""/> : room.name.slice(0,2).toUpperCase()}</span><div><strong>{room.name}</strong><small>{room.role}</small></div>→</button>)}{!rooms.length && <div className="empty-state">Nenhum servidor.</div>}</div></section>}
    {view === "friends" && <section><form className="friend-search" onSubmit={sendFriendRequest}><span>@</span><input value={friendName} onChange={(event) => setFriendName(event.target.value)} placeholder="nomedeusuario"/><button className="primary">Adicionar</button></form><div className="people-list">{friends.map((friend) => <article className="clickable-person" key={friend.id} onClick={() => openUserCard(friend)}><Avatar person={friend}/><div><strong>{friend.displayName}</strong><small>@{friend.username} · {friend.customStatus || "Sem status"}</small></div><span className={isOnline(online, friend.id) ? "online-pill" : "offline-pill"}>{isOnline(online, friend.id) ? "Online" : "Offline"}</span><button onClick={(event) => { event.stopPropagation(); openDirect(friend); }}>Mensagem</button></article>)}</div></section>}
    {view === "requests" && <section className="people-list">{requests.map((request) => <article key={request.id}><Avatar person={request.sender}/><div><strong>{request.sender.displayName}</strong><small>@{request.sender.username}</small></div><button onClick={() => answerRequest(request.id,"accepted")}>Aceitar</button><button onClick={() => answerRequest(request.id,"rejected")}>Recusar</button></article>)}{!requests.length && <div className="empty-state">Nenhuma solicitação.</div>}</section>}
    {view === "themes" && <section className="theme-panel"><div className="theme-preview"><div className="preview-sidebar"/><div><h3>Seu FriendCord</h3><p>Opções leves de aparência e uso.</p></div></div><label>Estilo<select value={theme.mode} onChange={(event) => applyTheme({ ...theme, mode: event.target.value as Theme["mode"] })}><option value="gradient">Degradê</option><option value="solid">Cor única</option></select></label><label>Principal<input type="color" value={theme.primary} onChange={(event) => applyTheme({ ...theme, primary: event.target.value })}/></label><label>Secundária<input type="color" value={theme.secondary} onChange={(event) => applyTheme({ ...theme, secondary: event.target.value })}/></label><label>Fundo<input type="color" value={theme.surface} onChange={(event) => applyTheme({ ...theme, surface: event.target.value })}/></label><label>Modo compacto<input type="checkbox" checked={compact} onChange={(event) => { setCompact(event.target.checked); localStorage.setItem("friendcord_compact", String(event.target.checked)); }}/></label><button onClick={() => api("/preferences", { method: "PUT", body: JSON.stringify(theme) })}>Salvar</button></section>}
    {view === "admin" && <section className="admin-page"><div className="admin-banner">♛ Todos os servidores e administradores globais.</div><h2>Servidores — {adminRooms.length}</h2><div className="server-grid">{adminRooms.map((room) => <article className="server-card" key={room.id}><span>{room.name.slice(0,2).toUpperCase()}</span><div><strong>{room.name}</strong><small>Dono: @{room.owner} · {room.memberCount} membros</small></div><button onClick={async () => { await api(`/admin/rooms/${room.id}/join`, { method: "POST" }); await loadRooms(); openRoom(room.id); }}>Entrar</button></article>)}{!adminRooms.length && <div className="empty-state">Nenhum servidor retornado.</div>}</div><h2>Usuários e administradores</h2><div className="people-list">{adminUsers.map((person) => <article key={person.id}><Avatar person={person}/><div><strong>{person.displayName}</strong><small>@{person.username}</small></div><span>{person.siteRole === "superadmin" ? "Admin global" : "Usuário"}</span>{person.id !== user.id && <button onClick={() => changeSiteRole(person, person.siteRole === "superadmin" ? "user" : "superadmin")}>{person.siteRole === "superadmin" ? "Remover admin" : "Tornar admin"}</button>}</article>)}</div></section>}
    {view === "dm" && selectedUser && <section className={`dm-panel ${compact ? "compact-messages" : ""}`}><button className="dm-person" onClick={() => openUserCard(selectedUser)}><Avatar person={selectedUser}/><div><strong>{selectedUser.displayName}</strong><small>@{selectedUser.username} · {selectedUser.customStatus || (isOnline(online,selectedUser.id) ? "Online" : "Offline")}</small></div></button><section className="message-history dm-history" ref={historyRef}>{dmMessages.map((message) => <article className={message.author.id === user.id ? "own-message" : ""} key={message.id}><Avatar person={message.author}/><div className="message-content"><div><strong>{message.author.displayName}</strong><time>{new Date(message.createdAt).toLocaleString("pt-BR")}</time></div>{message.body && <MessageText body={message.body}/>} {message.attachment && <AttachmentView file={message.attachment}/>}</div></article>)}</section><Composer {...composerProps} onSend={() => send(true)} placeholder={`Mensagem para @${selectedUser.username}`}/></section>}
  </main></>}

  {view === "room" && <><aside className="server-rail"><button className="home-button" onClick={() => { rtc.leave(); setView("servers"); }}>⌂</button>{rooms.map((room) => <button key={room.id} className={room.id === roomId ? "active" : ""} onClick={() => openRoom(room.id)}>{room.iconUrl ? <img src={mediaUrl(room.iconUrl)} alt=""/> : room.name.slice(0,2).toUpperCase()}</button>)}</aside><aside className="channels"><header><div><small>SERVIDOR</small><strong>{currentRoom?.name}</strong></div><div className="server-actions">{canManage && <button onClick={() => { if (currentRoom) setServerForm({ name: currentRoom.name, icon: null, banner: null }); setModal("serverSettings"); }}>⚙</button>}{canManage && <button onClick={openRoles}>Cargos</button>}{canManage && <button onClick={createInvite}>Convidar</button>}</div></header><nav><div className="channel-title">CANAIS DE TEXTO {canManage && <button onClick={() => { setChannelForm({ name:"",kind:"text",restricted:false,allowedUserIds:[] }); setModal("channel"); }}>＋</button>}</div>{channels.filter((item) => item.kind === "text").map((item) => <div className={item.id === channelId ? "channel-row selected" : "channel-row"} key={item.id}><button onClick={() => setChannelId(item.id)}># {item.name}</button>{item.restricted && <span>🔒</span>}{canManage && <button onClick={() => openAccess(item.id)}>⚙</button>}</div>)}<div className="channel-title">CANAIS DE VOZ {canManage && <button onClick={() => { setChannelForm({ name:"",kind:"voice",restricted:false,allowedUserIds:[] }); setModal("channel"); }}>＋</button>}</div>{channels.filter((item) => item.kind === "voice").map((item) => <div className="channel-row" key={item.id}><button onClick={() => { setChannelId(item.id); rtc.join(item.id,audioInputId,cameraId).catch((cause) => setError(friendlyPermission(cause))); }}>🎙️ {item.name}</button>{item.restricted && <span>🔒</span>}{canManage && <button onClick={() => openAccess(item.id)}>⚙</button>}</div>)}</nav>{rtc.inCall && <section className="voice-dock"><strong>📶 Voz conectada</strong><small>{currentChannel?.name}</small><div><button onClick={rtc.toggleAudio}>{rtc.audioEnabled ? "🎙️" : "🔇"}</button><button onClick={share}>🖥️</button><button onClick={() => setShowMedia(!showMedia)}>♫</button><button className="danger" onClick={rtc.leave}>☎</button></div></section>}<footer><Avatar person={user}/><button className="profile-summary" onClick={openProfile}><strong>{user.displayName}</strong><small>@{user.username}</small></button><button onClick={() => setView("servers")}>⌂</button></footer></aside><main className={`chat-main ${compact ? "compact-messages" : ""}`}><header><div><small>{currentChannel?.kind === "voice" ? "CANAL DE VOZ" : "CANAL DE TEXTO"}</small><h2>{currentChannel?.kind === "voice" ? "🎙️" : "#"} {currentChannel?.name}</h2></div>{error && <button className="notice" onClick={() => setError("")}>{error} ×</button>}</header>
    {rtc.inCall && <section className="call"><div className="videos">{rtc.localStream && <VideoTile stream={rtc.localStream} muted label="Você" avatarUrl={user.avatarUrl} videoVisible={rtc.videoEnabled || rtc.screenSharing} screenSharing={rtc.screenSharing}/>} {rtc.remotePeers.map((peer) => <VideoTile key={peer.id} stream={peer.stream} volume={volume} outputDeviceId={audioOutputId} label={peer.user.displayName} avatarUrl={peer.user.avatarUrl} videoVisible={peer.videoEnabled || peer.screenSharing} screenSharing={peer.screenSharing}/>)}</div><div className="call-controls"><button onClick={rtc.toggleAudio}>{rtc.audioEnabled ? "🎙️ Mutar" : "🔇 Desmutar"}</button><button onClick={() => rtc.toggleVideo()}>📷 Câmera</button><select value={quality} onChange={(event) => setQuality(event.target.value)}><option value="1280x720x30">720p/30</option><option value="1920x1080x30">1080p/30</option><option value="1920x1080x60">1080p/60</option></select>{rtc.screenSharing ? <button onClick={rtc.stopScreen}>⏹ Parar tela</button> : <button onClick={share}>🖥 Compartilhar</button>}<button onClick={toggleCallRecording}>⏺ Gravar</button><button onClick={() => setShowMedia(!showMedia)}>♫ Mídia</button><label>Volume<input type="range" min="0" max="1" step=".05" value={volume} onChange={(event) => setVolume(Number(event.target.value))}/></label><button className="danger" onClick={rtc.leave}>Sair</button></div>{showMedia && <MediaRoom channelId={channelId}/>}</section>}
    {currentChannel?.kind === "text" && <><section className="message-history" ref={historyRef}>{messages.map((message) => <article className={message.author.id === user.id ? "own-message" : ""} key={message.id}><button className="avatar-button" onClick={() => openUserCard(message.author)}><Avatar person={message.author}/></button><div className="message-content"><div><button className="author-button" onClick={() => openUserCard(message.author)}>{message.author.displayName}</button><time>{new Date(message.createdAt).toLocaleString("pt-BR")}</time></div>{message.body && <MessageText body={message.body}/>} {message.attachment && <AttachmentView file={message.attachment}/>}</div></article>)}</section><Composer {...composerProps} onSend={() => send(false)} placeholder={`Mensagem em #${currentChannel.name}`}/></>}
  </main><aside className="members"><h3>ONLINE — {members.filter((member) => isOnline(online,member.id)).length}</h3>{members.filter((member) => isOnline(online,member.id)).map((member) => <button className="member" key={member.id} onClick={() => openUserCard(member)}><span className="status online"/><Avatar person={member}/><div><strong>{member.displayName}</strong><small>{member.customStatus || `@${member.username}`}</small></div></button>)}<h3>OFFLINE — {members.filter((member) => !isOnline(online,member.id)).length}</h3>{members.filter((member) => !isOnline(online,member.id)).map((member) => <button className="member offline-member" key={member.id} onClick={() => openUserCard(member)}><span className="status"/><Avatar person={member}/><div><strong>{member.displayName}</strong><small>@{member.username}</small></div></button>)}</aside></>}

  {modal === "server" && <Modal title="Criar servidor" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createServer}><input autoFocus value={serverName} onChange={(event) => setServerName(event.target.value)} placeholder="Nome do servidor"/><button>Criar</button></form></Modal>}
  {modal === "invite" && <Modal title="Entrar em servidor" onClose={() => setModal(null)}><form className="modal-form" onSubmit={joinServer}><input autoFocus value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} placeholder="Código ou link"/><button>Entrar</button></form></Modal>}
  {modal === "inviteLink" && <Modal title="Convite" onClose={() => setModal(null)}><div className="modal-form copy-row"><input readOnly value={inviteLink}/><button onClick={() => navigator.clipboard.writeText(inviteLink)}>Copiar</button></div></Modal>}
  {modal === "userCard" && selectedUser && <Modal title="Perfil" onClose={() => setModal(null)}><div className="user-card"><Avatar person={selectedUser} size="large"/><h2>{selectedUser.displayName}</h2><p>@{selectedUser.username}</p><span>{isOnline(online,selectedUser.id) ? "Online" : "Offline"}</span><blockquote>{selectedUser.customStatus || "Sem status."}</blockquote><div className="action-row"><button onClick={() => openDirect(selectedUser)}>Mensagem privada</button>{!friends.some((friend) => friend.id === selectedUser.id) && <button onClick={() => sendFriendRequest(undefined,selectedUser.username)}>Adicionar amigo</button>}</div></div></Modal>}
  {modal === "code" && <Modal title="Inserir código formatado" onClose={() => setModal(null)}><div className="modal-form"><textarea className="code-editor" autoFocus rows={12} value={codeDraft} onChange={(event) => setCodeDraft(event.target.value)} placeholder="Digite ou cole o código..."/><button onClick={() => { if (codeDraft.trim()) setBody((current) => `${current}${current ? "\n" : ""}\`\`\`\n${codeDraft}\n\`\`\``); setCodeDraft(""); setModal(null); }}>Inserir</button></div></Modal>}
  {modal === "profile" && <Modal title="Meu perfil e dispositivos" onClose={() => setModal(null)}><form className="modal-form" onSubmit={saveProfile}><label>Nome<input value={profileForm.displayName} onChange={(event) => setProfileForm({...profileForm,displayName:event.target.value})}/></label><label>Usuário<input value={profileForm.username} onChange={(event) => setProfileForm({...profileForm,username:event.target.value})}/></label><label>Status<input value={profileForm.customStatus} onChange={(event) => setProfileForm({...profileForm,customStatus:event.target.value})}/></label><label>Foto<input type="file" accept="image/*" onChange={(event) => setProfileForm({...profileForm,avatar:event.target.files?.[0] ?? null})}/></label><label>Capa<input type="file" accept="image/*" onChange={(event) => setProfileForm({...profileForm,banner:event.target.files?.[0] ?? null})}/></label><label>Microfone<select value={audioInputId} onChange={(event) => setAudioInputId(event.target.value)}><option value="">Padrão</option>{devices.filter((item) => item.kind === "audioinput").map((item,index) => <option key={item.deviceId} value={item.deviceId}>{item.label || `Microfone ${index+1}`}</option>)}</select></label><label>Saída<select value={audioOutputId} onChange={(event) => setAudioOutputId(event.target.value)}><option value="">Padrão</option>{devices.filter((item) => item.kind === "audiooutput").map((item,index) => <option key={item.deviceId} value={item.deviceId}>{item.label || `Saída ${index+1}`}</option>)}</select></label><label>Câmera<select value={cameraId} onChange={(event) => setCameraId(event.target.value)}><option value="">Padrão</option>{devices.filter((item) => item.kind === "videoinput").map((item,index) => <option key={item.deviceId} value={item.deviceId}>{item.label || `Câmera ${index+1}`}</option>)}</select></label><button>Salvar</button></form></Modal>}
  {modal === "serverSettings" && <Modal title="Servidor" onClose={() => setModal(null)}><form className="modal-form" onSubmit={saveServer}><label>Nome<input value={serverForm.name} onChange={(event) => setServerForm({...serverForm,name:event.target.value})}/></label><label>Ícone<input type="file" accept="image/*" onChange={(event) => setServerForm({...serverForm,icon:event.target.files?.[0] ?? null})}/></label><label>Capa<input type="file" accept="image/*" onChange={(event) => setServerForm({...serverForm,banner:event.target.files?.[0] ?? null})}/></label><button>Salvar</button></form></Modal>}
  {modal === "channel" && <Modal title="Criar canal" onClose={() => setModal(null)}><form className="modal-form" onSubmit={createChannel}><input value={channelForm.name} onChange={(event) => setChannelForm({...channelForm,name:event.target.value})} placeholder="Nome"/><select value={channelForm.kind} onChange={(event) => setChannelForm({...channelForm,kind:event.target.value as "text"|"voice"})}><option value="text">Texto</option><option value="voice">Voz</option></select><label><input type="checkbox" checked={channelForm.restricted} onChange={(event) => setChannelForm({...channelForm,restricted:event.target.checked})}/> Canal privado</label>{channelForm.restricted && <MemberChecks members={members} selected={channelForm.allowedUserIds} toggle={toggleAllowed}/>}<button>Criar</button></form></Modal>}
  {modal === "access" && <Modal title="Privacidade do canal" onClose={() => setModal(null)}><div className="modal-form"><MemberChecks members={members} selected={channelForm.allowedUserIds} toggle={toggleAllowed}/><button onClick={saveAccess}>Salvar</button></div></Modal>}
  {modal === "roles" && <Modal title="Cargos e permissões" onClose={() => setModal(null)}><div className="modal-form roles-panel"><h3>Membros</h3>{members.map((person) => <label className="role-member" key={person.id}><Avatar person={person}/><span>{person.displayName}</span>{person.role === "owner" ? <b>Dono</b> : <select value={person.role ?? "member"} onChange={(event) => changeMemberRole(person,event.target.value as "admin"|"member")}><option value="admin">Administrador</option><option value="member">Membro</option></select>}</label>)}{(["admin","member"] as const).map((role) => <section className="permission-card" key={role}><h3>{role}</h3>{Object.entries({manageChannels:"Gerenciar canais",manageMembers:"Gerenciar membros",createInvites:"Criar convites",sendMessages:"Enviar mensagens",connectVoice:"Entrar na voz"}).map(([key,label]) => <label key={key}><input type="checkbox" checked={rolePermissions[role][key as keyof RolePermissions]} onChange={(event) => setRolePermissions((current) => ({...current,[role]:{...current[role],[key]:event.target.checked}}))}/>{label}</label>)}<button onClick={() => saveRole(role)}>Salvar cargo</button></section>)}</div></Modal>}
  </div>;
}

function MemberChecks({ members, selected, toggle }: { members: PublicUser[]; selected: string[]; toggle: (id: string) => void }) { return <div className="member-checks">{members.map((member) => <label key={member.id}><input type="checkbox" checked={selected.includes(member.id)} onChange={() => toggle(member.id)}/><Avatar person={member}/><span>{member.displayName}<small>@{member.username}</small></span></label>)}</div>; }
