import { useEffect, useRef, useState } from "react";
import type { MediaState } from "@friendcord/shared";
import { getSocket } from "../socket";
declare global { interface Window { YT?: { Player: new (element: HTMLElement, options: object) => YouTubePlayer }; onYouTubeIframeAPIReady?: () => void } }
interface YouTubePlayer { playVideo(): void; pauseVideo(): void; seekTo(seconds: number, allowSeekAhead: boolean): void; getCurrentTime(): number; destroy(): void }
function extract(input: string, provider: "youtube" | "spotify") { if (provider === "youtube") return input.match(/(?:v=|youtu\.be\/|embed\/)([\w-]{11})/)?.[1] ?? input.trim(); return input.match(/(?:track|episode|playlist|album)\/([\w]+)/)?.[1] ?? input.trim(); }
export function MediaRoom({ channelId }: { channelId: string }) { const [provider, setProvider] = useState<"youtube" | "spotify">("youtube"); const [input, setInput] = useState(""); const [state, setState] = useState<MediaState | null>(null); const host = useRef<HTMLDivElement>(null); const player = useRef<YouTubePlayer | null>(null);
  const publish = (patch: Partial<MediaState>) => { if (!state) return; const next = { ...state, ...patch, positionSeconds: player.current?.getCurrentTime() ?? state.positionSeconds, updatedAt: Date.now() }; setState(next); getSocket().emit("media:update", { channelId, state: next }); };
  useEffect(() => { const receive = (next: MediaState) => setState(next); getSocket().on("media:state", receive); return () => { getSocket().off("media:state", receive); }; }, []);
  useEffect(() => { if (!state || state.provider !== "youtube" || !host.current) return; const create = () => { player.current?.destroy(); player.current = new window.YT!.Player(host.current!, { videoId: state.mediaId, playerVars: { origin: location.origin }, events: { onReady: () => { player.current?.seekTo(state.positionSeconds + (state.playing ? (Date.now() - state.updatedAt) / 1000 : 0), true); state.playing ? player.current?.playVideo() : player.current?.pauseVideo(); } } }); }; if (window.YT) create(); else { window.onYouTubeIframeAPIReady = create; if (!document.querySelector("script[src*='youtube.com/iframe_api']")) { const script = document.createElement("script"); script.src = "https://www.youtube.com/iframe_api"; document.head.appendChild(script); } } return () => player.current?.destroy(); }, [state?.mediaId, state?.provider]);
  useEffect(() => { if (state?.provider === "youtube" && player.current) { player.current.seekTo(state.positionSeconds + (state.playing ? (Date.now() - state.updatedAt) / 1000 : 0), true); state.playing ? player.current.playVideo() : player.current.pauseVideo(); } }, [state?.playing, state?.positionSeconds, state?.updatedAt]);
  const load = () => { const next: MediaState = { provider, mediaId: extract(input, provider), playing: false, positionSeconds: 0, updatedAt: Date.now() }; setState(next); getSocket().emit("media:update", { channelId, state: next }); };
  return <section className="media-room"><div className="media-form"><select value={provider} onChange={(event) => setProvider(event.target.value as typeof provider)}><option value="youtube">YouTube</option><option value="spotify">Spotify</option></select><input placeholder="Cole o link oficial" value={input} onChange={(event) => setInput(event.target.value)}/><button onClick={load}>Carregar</button>{state?.provider === "youtube" && <><button onClick={() => publish({ playing: true })}>▶</button><button onClick={() => publish({ playing: false })}>⏸</button></>}</div>{state?.provider === "youtube" && <div className="embed" ref={host}/>} {state?.provider === "spotify" && <iframe className="embed" src={`https://open.spotify.com/embed/track/${state.mediaId}`} allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"/>}<small>Players oficiais. Anúncios e regras da conta continuam valendo; nenhum conteúdo é baixado ou retransmitido.</small></section>; }
