import { useEffect, useRef, useState } from "react";
import type { MediaState } from "@friendcord/shared";
import { getSocket } from "../socket";

declare global { interface Window { YT?: { Player: new (element: HTMLElement, options: object) => YouTubePlayer }; onYouTubeIframeAPIReady?: () => void } }
interface YouTubePlayer { playVideo(): void; pauseVideo(): void; stopVideo(): void; seekTo(seconds: number, allowSeekAhead: boolean): void; getCurrentTime(): number; mute(): void; unMute(): void; destroy(): void }
type QueueItem = { provider: "youtube" | "spotify"; mediaId: string; mediaType: string };
function extract(input: string, provider: "youtube" | "spotify"): QueueItem { if (provider === "youtube") return { provider, mediaId: input.match(/(?:v=|youtu\.be\/|embed\/)([\w-]{11})/)?.[1] ?? input.trim(), mediaType: "video" }; const match = input.match(/(track|episode|playlist|album)\/([\w]+)/); return { provider, mediaType: match?.[1] ?? "track", mediaId: match?.[2] ?? input.trim() }; }

export function MediaRoom({ channelId }: { channelId: string }) {
  const [provider, setProvider] = useState<"youtube" | "spotify">("youtube"); const [scope, setScope] = useState<"solo" | "room">("solo"); const [input, setInput] = useState(""); const [state, setState] = useState<MediaState | null>(null); const [queue, setQueue] = useState<QueueItem[]>([]); const [muted, setMuted] = useState(false); const [collapsed, setCollapsed] = useState(false); const host = useRef<HTMLDivElement>(null); const player = useRef<YouTubePlayer | null>(null);
  const send = (next: MediaState) => { setState(next); if (scope === "room") getSocket().emit("media:update", { channelId, state: next }); };
  const publish = (patch: Partial<MediaState>) => { if (!state) return; send({ ...state, ...patch, positionSeconds: player.current?.getCurrentTime() ?? state.positionSeconds, updatedAt: Date.now() }); };
  useEffect(() => { const receive = (next: MediaState) => { setScope("room"); setState(next); }; getSocket().on("media:state", receive); return () => { getSocket().off("media:state", receive); }; }, []);
  useEffect(() => { if (!state || state.provider !== "youtube" || !host.current) return; const create = () => { player.current?.destroy(); player.current = new window.YT!.Player(host.current!, { videoId: state.mediaId, playerVars: { origin: location.origin }, events: { onReady: () => { player.current?.seekTo(state.positionSeconds, true); state.playing ? player.current?.playVideo() : player.current?.pauseVideo(); if (muted) player.current?.mute(); } } }); }; if (window.YT) create(); else { window.onYouTubeIframeAPIReady = create; if (!document.querySelector("script[src*='youtube.com/iframe_api']")) { const script = document.createElement("script"); script.src = "https://www.youtube.com/iframe_api"; document.head.appendChild(script); } } return () => player.current?.destroy(); }, [state?.mediaId, state?.provider]);
  useEffect(() => { if (muted) player.current?.mute(); else player.current?.unMute(); }, [muted]);
  const load = (item = extract(input, provider)) => { const next: MediaState = { ...item, playing: false, positionSeconds: 0, updatedAt: Date.now() }; send(next); setInput(""); };
  const addQueue = () => { if (!input.trim()) return; setQueue((items) => [...items, extract(input, provider)]); setInput(""); };
  const next = () => { const [first, ...rest] = queue; if (!first) return; setQueue(rest); load(first); };
  if (collapsed) return <button className="media-bot-bubble" onClick={() => setCollapsed(false)}>♫ Abrir bot de mídia</button>;
  return <section className="media-room floating-media"><header><strong>♫ Bot de mídia oficial</strong><button onClick={() => setCollapsed(true)}>Ocultar</button></header><div className="media-form"><select value={provider} onChange={(event) => setProvider(event.target.value as typeof provider)}><option value="youtube">YouTube</option><option value="spotify">Spotify</option></select><select value={scope} onChange={(event) => setScope(event.target.value as typeof scope)}><option value="solo">Só para mim</option><option value="room">Sincronizar na sala</option></select><input placeholder="Cole o link oficial" value={input} onChange={(event) => setInput(event.target.value)}/><button onClick={() => load()}>Tocar</button><button onClick={addQueue}>＋ Fila</button></div>{state?.provider === "youtube" && <div className="embed" ref={host}/>} {state?.provider === "spotify" && <iframe className="embed" src={`https://open.spotify.com/embed/${state.mediaType ?? "track"}/${state.mediaId}`} allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"/>}<div className="media-controls"><button onClick={() => publish({ playing: true })}>▶</button><button onClick={() => publish({ playing: false })}>⏸</button><button onClick={() => { player.current?.stopVideo(); publish({ playing: false, positionSeconds: 0 }); }}>⏹</button><button onClick={() => setMuted(!muted)}>{muted ? "🔇 Desmutar para mim" : "🔊 Silenciar para mim"}</button><button onClick={next}>Próximo ({queue.length})</button></div><small>Modo sala sincroniza os players oficiais; não baixa nem retransmite conteúdo. Anúncios e regras da conta continuam valendo.</small></section>;
}
