import { useCallback, useEffect, useRef, useState } from "react";
import type { PublicUser } from "@friendcord/shared";
import { getSocket } from "../socket";

type Quality = { width: number; height: number; frameRate: number };
export interface RemotePeer { id: string; stream: MediaStream; user: PublicUser; audioEnabled: boolean; videoEnabled: boolean; screenSharing: boolean }
const iceServers: RTCIceServer[] = [{ urls: import.meta.env.VITE_STUN_URL ?? "stun:stun.l.google.com:19302" }, ...(import.meta.env.VITE_TURN_URL ? [{ urls: import.meta.env.VITE_TURN_URL, username: import.meta.env.VITE_TURN_USERNAME, credential: import.meta.env.VITE_TURN_CREDENTIAL }] : [])];

export function playSignal(kind: "join" | "leave" | "share" | "camera") {
  try {
    const Context = window.AudioContext || (window as typeof window & { webkitAudioContext: typeof AudioContext }).webkitAudioContext; const context = new Context(); const notes = kind === "join" ? [520, 720] : kind === "leave" ? [620, 420] : kind === "camera" ? [680, 840] : [760, 980];
    notes.forEach((frequency, index) => { const oscillator = context.createOscillator(); const gain = context.createGain(); const start = context.currentTime + index * 0.12; oscillator.frequency.value = frequency; oscillator.type = "sine"; gain.gain.setValueAtTime(0.0001, start); gain.gain.exponentialRampToValueAtTime(0.18, start + 0.02); gain.gain.exponentialRampToValueAtTime(0.0001, start + 0.14); oscillator.connect(gain).connect(context.destination); oscillator.start(start); oscillator.stop(start + 0.15); });
    setTimeout(() => context.close(), 500);
  } catch { /* som de interface opcional */ }
}

export function useWebRTC() {
  const [localStream, setLocalStream] = useState<MediaStream | null>(null); const [remotePeers, setRemotePeers] = useState<RemotePeer[]>([]); const [inCall, setInCall] = useState(false); const [callChannelId, setCallChannelId] = useState(""); const [screenSharing, setScreenSharing] = useState(false); const [audioEnabled, setAudioEnabled] = useState(true); const [videoEnabled, setVideoEnabled] = useState(false); const [noiseSuppression, setNoiseSuppression] = useState(true);
  const peers = useRef(new Map<string, RTCPeerConnection>()); const peerUsers = useRef(new Map<string, PublicUser>()); const peerStates = useRef(new Map<string, { audioEnabled: boolean; videoEnabled: boolean; screenSharing: boolean }>()); const channelRef = useRef<string | undefined>(undefined); const streamRef = useRef<MediaStream | null>(null); const screenTrackRef = useRef<MediaStreamTrack | null>(null); const cameraTrackRef = useRef<MediaStreamTrack | null>(null); const cameraDeviceRef = useRef<string | undefined>(undefined);
  const publishState = useCallback((next: { audioEnabled: boolean; videoEnabled: boolean; screenSharing: boolean }) => { if (channelRef.current) getSocket().emit("call:state", { channelId: channelRef.current, ...next }); }, []);
  const negotiate = useCallback(async (id: string, peer: RTCPeerConnection) => { const offer = await peer.createOffer(); await peer.setLocalDescription(offer); getSocket().emit("webrtc:signal", { target: id, signal: { description: peer.localDescription } }); }, []);
  const updateRemote = useCallback((id: string, stream?: MediaStream) => { const user = peerUsers.current.get(id) ?? { id, username: "participante", displayName: "Participante" }; const state = peerStates.current.get(id) ?? { audioEnabled: true, videoEnabled: false, screenSharing: false }; setRemotePeers((current) => { const previous = current.find((item) => item.id === id); return [...current.filter((item) => item.id !== id), { id, stream: stream ?? previous?.stream ?? new MediaStream(), user, ...state }]; }); }, []);
  const makePeer = useCallback((id: string) => { const existing = peers.current.get(id); if (existing) return existing; const peer = new RTCPeerConnection({ iceServers }); peers.current.set(id, peer); peer.onicecandidate = ({ candidate }) => candidate && getSocket().emit("webrtc:signal", { target: id, signal: { candidate } }); peer.ontrack = ({ streams }) => updateRemote(id, streams[0]); peer.onconnectionstatechange = () => { if (["failed", "closed", "disconnected"].includes(peer.connectionState)) { peer.close(); peers.current.delete(id); setRemotePeers((items) => items.filter((item) => item.id !== id)); } }; streamRef.current?.getTracks().forEach((track) => peer.addTrack(track, streamRef.current!)); return peer; }, [updateRemote]);
  const finishScreenSharing = useCallback((screenTrack: MediaStreamTrack) => { if (screenTrackRef.current !== screenTrack) return; screenTrackRef.current = null; setScreenSharing(false); publishState({ audioEnabled, videoEnabled, screenSharing: false }); const cameraTrack = cameraTrackRef.current; streamRef.current?.removeTrack(screenTrack); if (cameraTrack && !streamRef.current?.getVideoTracks().includes(cameraTrack)) streamRef.current?.addTrack(cameraTrack); if (streamRef.current) setLocalStream(new MediaStream(streamRef.current.getTracks())); void Promise.all([...peers.current.values()].map(async (peer) => { const sender = peer.getSenders().find((item) => item.track?.kind === "video"); if (sender) await sender.replaceTrack(cameraTrack?.enabled ? cameraTrack : null); })).catch(() => undefined); playSignal("share"); }, [audioEnabled, publishState, videoEnabled]);
  const stopScreen = useCallback(() => { const track = screenTrackRef.current; if (!track) return; track.stop(); finishScreenSharing(track); }, [finishScreenSharing]);
  const disconnect = useCallback(() => { const wasInCall = !!channelRef.current; if (channelRef.current) getSocket().emit("call:leave", channelRef.current); peers.current.forEach((peer) => peer.close()); peers.current.clear(); peerUsers.current.clear(); peerStates.current.clear(); streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; screenTrackRef.current = null; cameraTrackRef.current = null; channelRef.current = undefined; setCallChannelId(""); setLocalStream(null); setRemotePeers([]); setInCall(false); setScreenSharing(false); setAudioEnabled(true); setVideoEnabled(false); if (wasInCall) playSignal("leave"); }, []);
  const join = useCallback(async (channelId: string, inputDeviceId?: string, cameraDeviceId?: string) => { if (channelRef.current === channelId) return; disconnect(); cameraDeviceRef.current = cameraDeviceId; let stream = new MediaStream(); let microphoneAvailable = false; try { stream = await navigator.mediaDevices.getUserMedia({ audio: { deviceId: inputDeviceId ? { exact: inputDeviceId } : undefined, echoCancellation: true, noiseSuppression, autoGainControl: true }, video: false }); microphoneAvailable = stream.getAudioTracks().length > 0; } catch (error) { console.warn("Entrada de microfone indisponível; entrando como ouvinte.", error); } const audioTrack = stream.getAudioTracks()[0]; if (audioTrack && "contentHint" in audioTrack) audioTrack.contentHint = "speech"; streamRef.current = stream; setLocalStream(new MediaStream(stream.getTracks())); channelRef.current = channelId; setCallChannelId(channelId); setInCall(true); setAudioEnabled(microphoneAvailable); setVideoEnabled(false); const socket = getSocket(); socket.emit("call:join", channelId); socket.emit("call:state", { channelId, audioEnabled: microphoneAvailable, videoEnabled: false, screenSharing: false }); playSignal("join"); }, [disconnect, noiseSuppression]);
  const toggleNoiseSuppression = useCallback(async () => { const next = !noiseSuppression; const track = streamRef.current?.getAudioTracks()[0]; if (track) await track.applyConstraints({ echoCancellation: true, noiseSuppression: next, autoGainControl: true, channelCount: 1, sampleRate: 48000 }); setNoiseSuppression(next); return next; }, [noiseSuppression]);
  const switchAudioInput = useCallback(async (deviceId?: string) => { if (!streamRef.current) return; const replacementStream = await navigator.mediaDevices.getUserMedia({ audio: { deviceId: deviceId ? { exact: deviceId } : undefined, echoCancellation: true, noiseSuppression, autoGainControl: true, channelCount: 1, sampleRate: 48000 }, video: false }); const replacement = replacementStream.getAudioTracks()[0]; const previous = streamRef.current.getAudioTracks()[0]; replacement.enabled = previous?.enabled ?? true; if ("contentHint" in replacement) replacement.contentHint = "speech"; for (const peer of peers.current.values()) { const sender = peer.getSenders().find((item) => item.track?.kind === "audio"); if (sender) await sender.replaceTrack(replacement); else peer.addTrack(replacement, streamRef.current); } if (previous) { streamRef.current.removeTrack(previous); previous.stop(); } streamRef.current.addTrack(replacement); setLocalStream(new MediaStream(streamRef.current.getTracks())); }, [noiseSuppression]);
  const toggleAudio = useCallback(async () => { let track = streamRef.current?.getAudioTracks()[0]; if (!track && streamRef.current) { const microphone = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression, autoGainControl: true }, video: false }); track = microphone.getAudioTracks()[0]; if (track) { if ("contentHint" in track) track.contentHint = "speech"; streamRef.current.addTrack(track); for (const [id, peer] of peers.current) { peer.addTrack(track, streamRef.current); await negotiate(id, peer); } setLocalStream(new MediaStream(streamRef.current.getTracks())); } } if (!track) return false; track.enabled = !audioEnabled; setAudioEnabled(track.enabled); publishState({ audioEnabled: track.enabled, videoEnabled, screenSharing }); return track.enabled; }, [audioEnabled, negotiate, noiseSuppression, publishState, screenSharing, videoEnabled]);
  const toggleVideo = useCallback(async () => { if (!streamRef.current) return false; let track = cameraTrackRef.current; if (!track) { const camera = await navigator.mediaDevices.getUserMedia({ video: { deviceId: cameraDeviceRef.current ? { exact: cameraDeviceRef.current } : undefined, width: { ideal: 1280 }, height: { ideal: 720 }, frameRate: { ideal: 30 } }, audio: false }); track = camera.getVideoTracks()[0]; cameraTrackRef.current = track; streamRef.current.addTrack(track); for (const [id, peer] of peers.current) { peer.addTrack(track, streamRef.current); await negotiate(id, peer); } } else track.enabled = !track.enabled; const enabled = track.enabled; setVideoEnabled(enabled); setLocalStream(new MediaStream(streamRef.current.getTracks())); publishState({ audioEnabled, videoEnabled: enabled, screenSharing }); return enabled; }, [audioEnabled, negotiate, publishState, screenSharing]);
  const shareScreen = useCallback(async (quality: Quality) => { if (!streamRef.current || screenTrackRef.current) return; const display = await navigator.mediaDevices.getDisplayMedia({ video: { width: { ideal: quality.width }, height: { ideal: quality.height }, frameRate: { ideal: quality.frameRate, max: quality.frameRate } }, audio: true }); const screenTrack = display.getVideoTracks()[0]; if ("contentHint" in screenTrack) screenTrack.contentHint = "detail"; screenTrackRef.current = screenTrack; const oldVisibleTrack = streamRef.current.getVideoTracks()[0]; if (oldVisibleTrack) streamRef.current.removeTrack(oldVisibleTrack); streamRef.current.addTrack(screenTrack); setLocalStream(new MediaStream(streamRef.current.getTracks())); setScreenSharing(true); publishState({ audioEnabled, videoEnabled, screenSharing: true }); playSignal("share"); screenTrack.onended = () => finishScreenSharing(screenTrack); void Promise.all([...peers.current.entries()].map(async ([id, peer]) => { let sender = peer.getSenders().find((item) => item.track?.kind === "video"); if (sender) await sender.replaceTrack(screenTrack); else { sender = peer.addTrack(screenTrack, streamRef.current!); await negotiate(id, peer); } const parameters = sender.getParameters(); parameters.encodings = parameters.encodings?.length ? parameters.encodings : [{}]; parameters.encodings[0].maxBitrate = quality.height >= 2160 ? 25_000_000 : quality.height >= 1440 ? 16_000_000 : 10_000_000; parameters.degradationPreference = "maintain-resolution"; await sender.setParameters(parameters).catch(() => undefined); })).catch(() => undefined); }, [audioEnabled, finishScreenSharing, negotiate, publishState, videoEnabled]);
  useEffect(() => { const socket = getSocket(); const peerJoined = async ({ socketId, user }: { socketId: string; user: PublicUser }) => { peerUsers.current.set(socketId, user); updateRemote(socketId); const peer = makePeer(socketId); await negotiate(socketId, peer); playSignal("join"); }; const signal = async ({ from, signal }: { from: string; signal: unknown }) => { const peer = makePeer(from); const data = signal as { description?: RTCSessionDescriptionInit; candidate?: RTCIceCandidateInit }; try { if (data.description) { await peer.setRemoteDescription(data.description); if (data.description.type === "offer") { const answer = await peer.createAnswer(); await peer.setLocalDescription(answer); socket.emit("webrtc:signal", { target: from, signal: { description: peer.localDescription } }); } } else if (data.candidate) await peer.addIceCandidate(data.candidate); } catch (error) { console.warn("Sinal WebRTC ignorado", error); } }; const left = ({ socketId }: { socketId: string }) => { peers.current.get(socketId)?.close(); peers.current.delete(socketId); peerUsers.current.delete(socketId); peerStates.current.delete(socketId); setRemotePeers((items) => items.filter((item) => item.id !== socketId)); playSignal("leave"); }; const state = ({ socketId, user, audioEnabled: remoteAudio, videoEnabled: remoteVideo, screenSharing: remoteScreen }: { socketId: string; user: PublicUser; audioEnabled: boolean; videoEnabled: boolean; screenSharing: boolean }) => { const previous = peerStates.current.get(socketId); peerUsers.current.set(socketId, user); peerStates.current.set(socketId, { audioEnabled: remoteAudio, videoEnabled: remoteVideo, screenSharing: remoteScreen }); updateRemote(socketId); if (previous && previous.screenSharing !== remoteScreen) playSignal("share"); if (previous && !previous.videoEnabled && remoteVideo) playSignal("camera"); }; socket.on("webrtc:peer-joined", peerJoined); socket.on("webrtc:signal", signal); socket.on("webrtc:peer-left", left); socket.on("call:state", state); return () => { socket.off("webrtc:peer-joined", peerJoined); socket.off("webrtc:signal", signal); socket.off("webrtc:peer-left", left); socket.off("call:state", state); }; }, [makePeer, negotiate, updateRemote]);
  useEffect(() => { const socket = getSocket(); const moderated = ({ action }: { action: "mute" | "stop-screen" }) => { if (action === "mute") { const track = streamRef.current?.getAudioTracks()[0]; if (track) { track.enabled = false; setAudioEnabled(false); publishState({ audioEnabled: false, videoEnabled, screenSharing }); } } else stopScreen(); }; socket.on("call:moderated", moderated); return () => { socket.off("call:moderated", moderated); }; }, [publishState, screenSharing, stopScreen, videoEnabled]);
  useEffect(() => {
    const socket = getSocket();
    const restoreCall = () => {
      const channelId = channelRef.current;
      if (!channelId) return;
      peers.current.forEach((peer) => peer.close());
      peers.current.clear();
      peerUsers.current.clear();
      peerStates.current.clear();
      setRemotePeers([]);
      const audioTrack = streamRef.current?.getAudioTracks()[0];
      const cameraTrack = cameraTrackRef.current;
      const screenTrack = screenTrackRef.current;
      socket.emit("call:join", channelId);
      socket.emit("call:state", { channelId, audioEnabled: !!audioTrack?.enabled, videoEnabled: !!cameraTrack?.enabled, screenSharing: !!screenTrack });
    };
    const resume = () => {
      if (!channelRef.current || document.visibilityState === "hidden") return;
      if (!socket.connected) socket.connect();
    };
    socket.on("connect", restoreCall);
    window.addEventListener("online", resume);
    window.addEventListener("focus", resume);
    document.addEventListener("visibilitychange", resume);
    return () => {
      socket.off("connect", restoreCall);
      window.removeEventListener("online", resume);
      window.removeEventListener("focus", resume);
      document.removeEventListener("visibilitychange", resume);
    };
  }, []);
  return { localStream, remotePeers, inCall, callChannelId, screenSharing, audioEnabled, videoEnabled, noiseSuppression, join, leave: () => undefined, disconnect, shareScreen, stopScreen, toggleAudio, toggleVideo, toggleNoiseSuppression, switchAudioInput };
}
