import { useCallback, useEffect, useRef, useState } from "react";
import { getSocket } from "../socket";

type Quality = { width: number; height: number; frameRate: number };
export interface RemotePeer { id: string; stream: MediaStream }
const iceServers: RTCIceServer[] = [{ urls: import.meta.env.VITE_STUN_URL ?? "stun:stun.l.google.com:19302" }, ...(import.meta.env.VITE_TURN_URL ? [{ urls: import.meta.env.VITE_TURN_URL, username: import.meta.env.VITE_TURN_USERNAME, credential: import.meta.env.VITE_TURN_CREDENTIAL }] : [])];

export function useWebRTC() {
  const [localStream, setLocalStream] = useState<MediaStream | null>(null); const [remotePeers, setRemotePeers] = useState<RemotePeer[]>([]); const [inCall, setInCall] = useState(false); const [screenSharing, setScreenSharing] = useState(false);
  const peers = useRef(new Map<string, RTCPeerConnection>()); const channelRef = useRef<string | undefined>(undefined); const streamRef = useRef<MediaStream | null>(null);
  const makePeer = useCallback((id: string) => { const existing = peers.current.get(id); if (existing) return existing; const peer = new RTCPeerConnection({ iceServers }); peers.current.set(id, peer); peer.onicecandidate = ({ candidate }) => candidate && getSocket().emit("webrtc:signal", { target: id, signal: { candidate } }); peer.ontrack = ({ streams }) => setRemotePeers((current) => [...current.filter((item) => item.id !== id), { id, stream: streams[0] }]); peer.onconnectionstatechange = () => { if (["failed", "closed", "disconnected"].includes(peer.connectionState)) { peer.close(); peers.current.delete(id); setRemotePeers((items) => items.filter((item) => item.id !== id)); } }; streamRef.current?.getTracks().forEach((track) => peer.addTrack(track, streamRef.current!)); return peer; }, []);
  const leave = useCallback(() => { if (channelRef.current) getSocket().emit("call:leave", channelRef.current); peers.current.forEach((peer) => peer.close()); peers.current.clear(); streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; setLocalStream(null); setRemotePeers([]); setInCall(false); setScreenSharing(false); }, []);
  const join = useCallback(async (channelId: string) => { leave(); const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true }, video: { width: 1280, height: 720, frameRate: 30 } }); streamRef.current = stream; setLocalStream(stream); channelRef.current = channelId; setInCall(true); getSocket().emit("call:join", channelId); }, [leave]);
  const shareScreen = useCallback(async (quality: Quality) => { const display = await navigator.mediaDevices.getDisplayMedia({ video: { width: { ideal: quality.width }, height: { ideal: quality.height }, frameRate: { ideal: quality.frameRate, max: quality.frameRate } }, audio: true }); const screenTrack = display.getVideoTracks()[0]; const cameraTrack = streamRef.current?.getVideoTracks()[0]; for (const peer of peers.current.values()) await peer.getSenders().find((sender) => sender.track?.kind === "video")?.replaceTrack(screenTrack); if (streamRef.current && cameraTrack) { streamRef.current.removeTrack(cameraTrack); streamRef.current.addTrack(screenTrack); setLocalStream(new MediaStream(streamRef.current.getTracks())); } setScreenSharing(true); screenTrack.onended = async () => { if (cameraTrack) { for (const peer of peers.current.values()) await peer.getSenders().find((sender) => sender.track?.kind === "video")?.replaceTrack(cameraTrack); streamRef.current?.removeTrack(screenTrack); streamRef.current?.addTrack(cameraTrack); if (streamRef.current) setLocalStream(new MediaStream(streamRef.current.getTracks())); } setScreenSharing(false); }; }, []);
  useEffect(() => { const socket = getSocket(); const peerJoined = async ({ socketId }: { socketId: string }) => { const peer = makePeer(socketId); const offer = await peer.createOffer(); await peer.setLocalDescription(offer); socket.emit("webrtc:signal", { target: socketId, signal: { description: peer.localDescription } }); }; const signal = async ({ from, signal }: { from: string; signal: unknown }) => { const peer = makePeer(from); const data = signal as { description?: RTCSessionDescriptionInit; candidate?: RTCIceCandidateInit }; try { if (data.description) { await peer.setRemoteDescription(data.description); if (data.description.type === "offer") { const answer = await peer.createAnswer(); await peer.setLocalDescription(answer); socket.emit("webrtc:signal", { target: from, signal: { description: peer.localDescription } }); } } else if (data.candidate) await peer.addIceCandidate(data.candidate); } catch (error) { console.warn("Sinal WebRTC ignorado", error); } }; const left = ({ socketId }: { socketId: string }) => { peers.current.get(socketId)?.close(); peers.current.delete(socketId); setRemotePeers((items) => items.filter((item) => item.id !== socketId)); }; socket.on("webrtc:peer-joined", peerJoined); socket.on("webrtc:signal", signal); socket.on("webrtc:peer-left", left); return () => { socket.off("webrtc:peer-joined", peerJoined); socket.off("webrtc:signal", signal); socket.off("webrtc:peer-left", left); }; }, [makePeer]);
  const toggle = (kind: "audio" | "video") => { const track = streamRef.current?.getTracks().find((item) => item.kind === kind); if (track) track.enabled = !track.enabled; return track?.enabled ?? false; };
  return { localStream, remotePeers, inCall, screenSharing, join, leave, shareScreen, toggle };
}
