name: Preparar FriendCord
on:
  push:
    paths:
      - FriendCord.zip
      - .github/workflows/unpack.yml
permissions:
  contents: write
jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extrair projeto
        run: |
          unzip -o FriendCord.zip
          rm -f FriendCord.zip
          rm -f .github/workflows/unpack.yml
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Preparar projeto para deploy [skip ci]"
          git push
